fix(build): avoid warning multiple times
mdn/yari pull request #10269
Opened 2024-01-05 08:42 UTC by awxiaoxian2020

## Summary

Fixes #10262.

### Problem

Warn `'BLOG_ROOT' not set in .env file` multiple times in console.

### Solution

Move warning to top level.
---

## Screenshots

### Before

### After

---

## How did you test this change?

2024-02-12 08:41 UTC, fiji-flo requested changes
Thanks a lot. Some minor changes because `findPostFileBySlug` is still used and it must return null. So it's cleaner if we check for `BLOG_ROOT` in there.

If you add my suggested changes this is great and we'll approve.

2024-02-12 08:41 UTC, fiji-flo commented on build/utils.ts
>  export function findPostFileBySlug(slug: string): string | null {
This is still used in other places so we just remove the warning.
```suggestion
export function findPostFileBySlug(slug: string): string | null {
  if (!BLOG_ROOT) {
    return null;
  }
```

2024-02-12 08:41 UTC, fiji-flo commented on build/spas.ts
> +            } else if (segment === "blog" && BLOG_ROOT) {
Not needed anymore since we keep returning `null`
```suggestion
            } else if (segment === "blog") {
```

2024-02-12 08:41 UTC, fiji-flo commented on build/spas.ts
> +  BLOG_ROOT,
```suggestion
```

2024-03-28 14:57 UTC, caugner approved these changes
LGTU (@argl @fiji-flo @caugner), thanks! 🎉

2024-03-28 14:58 UTC, merged