chore: add optional title, width, height attrs to YouTube embed
mdn/yari pull request #10504
Opened 2024-02-13 08:38 UTC by bsmth

## Summary

This PR adds a few more parameters to the YouTube embed macro.

### Problem

Currently the title, width and height are hardcoded, so it would be nice to be able to customize these.

### Solution

Add three optional parameters that fall back to current hardcoded values if not given.

---

## Screenshots

### Before

### After

---

## How did you test this change?

```
yarn && yarn dev
```

2024-02-28 13:22 UTC, caugner requested changes
Let's only add the title now, for accessibility, as the width/height is a separate issue.

2024-02-28 13:22 UTC, caugner commented on kumascript/macros/EmbedYouTube.ejs
> +//  $3  height (optional)
```suggestion
```

2024-02-28 13:22 UTC, caugner commented on kumascript/macros/EmbedYouTube.ejs
> +  `height="${$3 || 315}" ` +
```suggestion
var video = '<iframe width="560" height="315" ' +
  `src="https://www.youtube-nocookie.com/embed/${$0}" ` +
  `title="${$1 || 'YouTube video'}" ` +
```

2024-05-03 14:02 UTC, caugner approved these changes

2024-05-03 14:02 UTC, merged

2024-05-03 14:02 UTC, caugner commented
FYI @fiji-flo

2024-05-06 08:14 UTC, bsmth commented
Thank you!