feat(ssr): remove external files dependencies
mdn/yari pull request #10885
Opened 2024-04-09 14:23 UTC by fiji-flo

## Summary
Before the ssr dist had dependencies on external files (e.g. index.html).

By in-lining those dependencies we can generate a portable standalone main.js.

This also fixed our font preloading logic.

### Problem

Using the SSR main.js outside of yari failed because of external dependencies.

### Solution

Add a build script and inline dependencies.

---

## How did you test this change?

Locally and about to deploy to stage.

2024-04-22 12:41 UTC, fiji-flo commented on client/config/webpack.config.js
> +  const env = getClientEnvironment(
Rather remove trailing slash, than just removing the last char.

2024-04-22 12:41 UTC, fiji-flo commented on client/public/index.html
> +    <meta property="og:image" content="%BASE_URL%/mdn-social-share.png" />
Using a new `%BASE_URL%` here because fixing `%PUBLIC_URL%` is tricky and dangerous.

2024-04-22 12:41 UTC, fiji-flo commented on client/scripts/postprocess-client-build.js
> +export async function hashSomeStaticFilesForClientBuild(buildRoot) {
Maybe this optimized in the past. Now it merely  hashes files.

2024-04-22 12:41 UTC, fiji-flo commented on package.json
> +    "build:prepare": "yarn build:client && yarn build:ssr && yarn tool popularities && yarn tool spas && yarn tool gather-git-history && yarn tool build-robots-txt",
optimize-client-build moved into the client build step.
google-analytics-code moved to SSR prepare.

2024-04-22 12:41 UTC, fiji-flo commented on ssr/prepare.ts
Extracted code from `ssr/render.ts`

2024-04-22 12:41 UTC, fiji-flo commented on ssr/webpack.config.js
> +        resourceQuery: /raw/,
Allows us to include the post processed index.html as string.

2024-04-23 11:41 UTC, caugner requested changes
On stage, on the [MDN Plus page](https://developer.allizom.org/en-US/plus) I’m seeing this error in the console, probably related to this PR:
> 13:37:41.826 Security Error: Content at https://developer.allizom.org/en-US/plus may not load or link to file:///home/runner/work/yari/yari/ssr/dist//distimages/7023cc01db35a3cf8c89371f0e78da61.png.

2024-04-24 19:24 UTC, LeoMcA approved these changes
Did a local diff between this and main, saw no differences other than those which were intentional. Looks good on staging.

Just one leftover `console.log`:

2024-04-24 19:24 UTC, LeoMcA commented on testing/tests/index.test.ts
> +    console.log("og:image", url);
Leftover?

2024-04-25 10:58 UTC, merged