Add color guides
mdn/yari pull request #10945
Opened 2024-04-17 23:04 UTC by estelle

## Summary

Adds the three color guides to the CSS guides section of the CSS sidebar

### Problem
These color guides are not listed in the CSS sidebar

### Solution

This adds the 3 guides

### Screenshots

<img width="326" alt="Screenshot of sidebar showing color guides" src="https://github.com/mdn/yari/assets/69888/8a9eb7f5-43ac-43b6-8363-2366cce779e5">

## How did you test this change?

localhost:5042
i clicked on all three links and the pages came up.

2024-04-17 23:18 UTC, caugner requested changes

2024-04-17 23:18 UTC, caugner commented on kumascript/macros/CSSRef.ejs
> +            <li><%-smartLink(`${cssURL}CSS_colors/Using_color_wisely`, null, text['Using_color_wisely'], cssURL)%></li>
Can you please check if this works? 🙏  (If so, we don't need the translations above.)

```suggestion
            <li><%-smartLink(`${cssURL}CSS_colors/Color_values`)%></li>
            <li><%-smartLink(`${cssURL}CSS_colors/Relative_colors`)%></li>
            <li><%-smartLink(`${cssURL}CSS_colors/Using_color_wisely`)%></li>
```

2024-04-19 14:56 UTC, caugner commented on kumascript/macros/CSSRef.ejs
> +        'Color_contrast': 'Accessibility: Color contrast',
```suggestion
        'Applying_color_to_HTML_elements_using_CSS': 'Applying color to HTML elements',
        'Web_Accessibility_Understanding_Colors_and_Luminance': 'Accessibility: Understanding colors and luminance',
        'Color_contrast': 'Accessibility: Color contrast',
```

2024-04-19 14:58 UTC, caugner approved these changes

2024-04-19 15:00 UTC, caugner commented
Putting in draft while the upstream PR is not merged yet.

@estelle Please mark the PR as "ready for review" again as soon as the content changes land. Thanks!

2024-04-25 22:06 UTC, estelle commented
@caugner https://github.com/mdn/content/pull/33071 has been merged!

2024-04-26 09:08 UTC, merged