chore(macros/gamessidebar): add russian translation
mdn/yari pull request #10984
Opened 2024-04-24 00:38 UTC by pseudopilot

## Summary

Add Russian translation to Games Sidebar.

### Problem

When Russian language is chosen the Games Sidebar is still shown in English

### Solution

Add Russian translation to `kumascript/macros/GamesSidebar.ejs`.

### Before

Games Sidebar is shown in "en-US" for Russian language content

### After

Games Sidebar is shown in "ru" for Russian language content

2024-04-24 18:02 UTC, caugner commented
@mdn/yari-content-ru Can you please take a look at these changes? 🙏

2024-04-24 20:58 UTC, leon-win commented
> @mdn/yari-content-ru Can you please take a look at these changes? 🙏

In progress =)

@caugner Is it possible to make this request editable for me?
I think it will be faster to make edits this way (now and in future PRs). In https://github.com/mdn/translated-content I can make changes to other people's PRs, but in https://github.com/mdn/yari/ I can only view =(

2024-04-24 21:42 UTC, caugner commented
@leon-win You should be able to click on the "Files changed" tab, then select one more lines you want to make suggestions for, then click the "Add a suggestion" button, edit the selected lines, then click on "Start your review" (for the first comment) or "Add review comment" (for the following ones), finally click "Finish your review" at the top right.

See also: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

Here's a screen recording showing the suggestion feature:
https://github.com/mdn/yari/assets/495429/3493c610-a40a-49d3-8757-ed7361b416cc

2024-04-24 22:08 UTC, leon-win requested changes

2024-04-24 22:08 UTC, leon-win commented on kumascript/macros/GamesSidebar.ejs
> +    "APIs_for_game_development": "APIs для разработки игр",
```suggestion
    "APIs_for_game_development": "API для разработки игр",
```

2024-04-24 22:08 UTC, leon-win commented on kumascript/macros/GamesSidebar.ejs
> +      "Optimizing_startup_performance": "Оптимизация производительности запуска",
```suggestion
      "Optimizing_startup_performance": "Оптимизация запуска",
```

2024-04-24 22:08 UTC, leon-win commented on kumascript/macros/GamesSidebar.ejs
> +      "Using_WebRTC_peer-to-peer_data_channels": "Использование каналов данных peer-to-peer WebRTC",
```suggestion
      "Using_WebRTC_peer-to-peer_data_channels": "Использование WebRTC для передачи данных",
```

2024-04-24 22:08 UTC, leon-win commented on kumascript/macros/GamesSidebar.ejs
> +      "Tiles_and_tilemaps_overview": "Обзор тайлов и тайлмапов",
```suggestion
      "2D_collision_detection": "Обнаружение столкновений в 2D",
      "Tiles_and_tilemaps_overview": "Обзор тайлов и тайловых карт",
```

2024-04-24 22:08 UTC, leon-win commented on kumascript/macros/GamesSidebar.ejs
> +      "Explaining_basic_3D_theory": "Объяснение основной 3D теории",
```suggestion
      "Explaining_basic_3D_theory": "Объяснение основ теории 3D",
```

2024-04-24 22:08 UTC, leon-win commented on kumascript/macros/GamesSidebar.ejs
> +      "Building_up_a_basic_demo_with_Three.js": "Создание базового демо с Three.js",
```suggestion
      "Building_up_a_basic_demo_with_A-Frame": "Создание базового демо с помощью A-Frame",
      "Building_up_a_basic_demo_with_Babylon.js": "Создание базового демо с помощью Babylon.js",
      "Building_up_a_basic_demo_with_PlayCanvas": "Создание базового демо с помощью PlayCanvas",
      "Building_up_a_basic_demo_with_Three.js": "Создание базового демо с помощью Three.js",
```

2024-04-24 22:08 UTC, leon-win commented on kumascript/macros/GamesSidebar.ejs
> +      "Bounding_volume_collision_detection_with_THREE.js": "Обнаружение столкновений объемов с THREE.js",
```suggestion
      "3D_collision_detection": "Обнаружение столкновений в 3D",
      "Bounding_volume_collision_detection_with_THREE.js": "Обнаружение столкновений объёмных фигур с помощью Three.js",
```

2024-04-24 22:08 UTC, leon-win commented on kumascript/macros/GamesSidebar.ejs
> +      "Desktop_with_gamepad": "Управление с геймпада",
```suggestion
      "Desktop_with_mouse_and_keyboard": "Управление с помощью мыши и клавиатуры",
      "Desktop_with_gamepad": "Управление с помощью геймпада",
```

2024-04-25 10:02 UTC, leon-win commented
@pseudopilot , спасибо за желание улучшить MDN!)

Несколько комментариев.

По поводу описания PR, если добавляешь секции `Before` и `After`, то они обычно подразумевают что-то более наглядное, то есть лучше там помещать скриншоты, как было и как стало. Тогда будет гораздо удобнее погружаться в суть того, что было сделано.

По поводу самих изменений: в этом репоизитории я не могу вносить изменения напрямую (а это на мой взгляд быстрее и проще), поэтому пришлось делать несколько suggest'ов, ты их принял (кстати об этом хорошо бы писать комментарий, чтобы было наглядно)) и теперь можно бы вливать изменения... но есть проблема:
![image](https://github.com/mdn/yari/assets/1682136/cea720e3-d499-4f2a-adf6-b4e2014e1baa)

То есть влить изменения с неподписанными коммитами не получится. Как подписывать коммиты можно прочитать в документации (https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification).

Наверное будет проще создать новую ветку и новый PR. Если нет возможности этим заниматься, то могу сделать я, мне будет недолго, так как изменения уже подготовлены и доработаны.

2024-04-25 20:58 UTC, pseudopilot commented
@leon-win , спасибо за пояснения. Я сделаю новый ПР.
Касательно скриншотов - я хотел их прикрепить, но у меня почему-то не получилось локально добиться обновления этого переведенного сайдбара, хотя локально проект запустился. Запускал по README.
Возможно, есть какие-то нюансы?

2024-04-25 21:09 UTC, leon-win commented
> @leon-win , спасибо за пояснения. Я сделаю новый ПР. Касательно скриншотов - я хотел их прикрепить, но у меня почему-то не получилось локально добиться обновления этого переведенного сайдбара, хотя локально проект запустился. Запускал по README. Возможно, есть какие-то нюансы?

Блин)))

Я только что (прямо несколько минут назад!) сделал https://github.com/mdn/yari/pull/11005

Посмотри его плиз, если есть замечания, напиши комментарий. А этот ПР закроем.

По поводу запуска `yari`: вроде особых нюансов нет, запускается командой `yari dev`:
![image](https://github.com/mdn/yari/assets/1682136/4965d4dd-591c-4735-887f-7e324fa8c3d0)

А что возникает при запуске, какие сообщения?

2024-04-25 21:12 UTC, pseudopilot commented
> Посмотри его плиз, если есть замечания, напиши комментарий. А этот ПР закроем.

Всё отлично, спасибо!
Попрактикуюсь с подписями на следующем ПР 😃

2024-04-25 21:17 UTC, leon-win commented
@caugner, close this PR please.

I created a similar request (https://github.com/mdn/yari/pull/11005) because this one was having problems with the merge due to signatures.

And if it’s not difficult, please answer my question above (about rights in this repository).

By the way, I can’t close this PR, as far as I understand this is also due to special access settings?

2024-04-25 22:21 UTC, pseudopilot commented
@leon-win , с запуском разобрался. В **.env** была закомментирована строка с адресом translated-content. 😃

2024-04-26 09:23 UTC, caugner approved these changes

2024-04-26 09:24 UTC, merged

2024-04-26 09:28 UTC, caugner commented
> Does it depend on the repository settings or do I just not have enough rights?

@leon-win Yes, you "only" have write access on the translated-content repo, but few people (mainly MDN staff) have this permission on the yari repo. But eventually we should have less translations in yari, because we want to migrate all sidebars to use `smartLink()`, which automatically uses the page's short-title or title in the locale.

2024-04-26 10:24 UTC, leon-win commented
> > Does it depend on the repository settings or do I just not have enough rights?
> 
> @leon-win Yes, you "only" have write access on the translated-content repo, but few people (mainly MDN staff) have this permission on the yari repo. But eventually we should have less translations in yari, because we want to migrate all sidebars to use `smartLink()`, which automatically uses the page's short-title or title in the locale.

Thank you for the explanation.
I think automatic generation sidebars from short-titles is good idea! :+1:

2024-04-26 19:34 UTC, caugner commented
> I think automatic generation sidebars from short-titles is good idea! 👍

The caveat is that you can then only have translated titles for the pages that are available in the current locale.

2024-04-26 19:50 UTC, leon-win commented
> > I think automatic generation sidebars from short-titles is good idea! 👍
> 
> The caveat is that you can then only have translated titles for the pages that are available in the current locale.

Those for which there is no translation will have English names. In my opinion there is no contradiction in this.
In addition, by analogy with other links for which there is no translation, we can add a postfix (`Some link without translation (англ.)`)