fix(css-syntax): fix some minor css syntax bugs
mdn/yari pull request #11070
Opened 2024-05-06 08:35 UTC by fiji-flo

## Summary

This includes some minor fixes for CSS syntax :
- link <length [0,∞]> to length
- link ! in [ a | b ]!
- prefer main spec for  at sytntax rule descriptors

---

## How did you test this change?

See https://static.fiji-flo.de/diff-part-2.html
-webkit-line-clamp/index.json is an example `<integer [1,∞]>` 
background-position-x/index.json is an example for the `]!`fix
@font-face/ascent-override/index.json is an example for using [css-fonts](https://github.com/w3c/webref/blob/curated/ed/css/css-fonts.json#L1307) instead of [css-fonts-5](https://github.com/w3c/webref/blob/curated/ed/css/css-fonts-5.json#L125)

2024-05-08 10:47 UTC, fiji-flo commented
@wbamberg are you fine with these? Especially the last one:
> - prefer main spec for at sytntax rule descriptors

2024-05-16 15:55 UTC, dipikabh commented
I took a quick look, @fiji-flo. The results in the right column on https://static.fiji-flo.de/diff-part-2.html look good.

To confirm, for "@page/index.json", will the part "Where the <page-body> includes:" be included in the Formal syntax?

2024-05-16 20:26 UTC, dipikabh commented
We should fix this in content (I'll make a note) to remove the hand-curated part following https://developer.mozilla.org/en-US/docs/Web/CSS/@page#formal_syntax. `<page-body>` is no longer relevant, and `<pseudo-page>` is getting covered in the syntax.

2024-06-05 17:09 UTC, caugner requested changes
LGTM, just two nits.

2024-06-05 17:09 UTC, caugner commented on kumascript/src/lib/css-syntax.ts
> +        const key = name.replace(/(^<|>$)/g, "").replace(/ ?\[.*\]$/, "");
```suggestion
        // Remove surrounding angle brackets, and range/choice brackets.
        const key = name.replace(/(^<|>$)/g, "").replace(/ ?\[.*\]$/, "");
```

2024-06-05 17:09 UTC, caugner commented on kumascript/src/lib/css-syntax.ts
> +          /\]([^']?)$/,
Is this causing this change:
<img width="640" alt="image" src="https://github.com/mdn/yari/assets/495429/9e5261e5-5637-4b1b-8b17-baa8367a4b12">

If this is intended, can we also fix it for the opening bracket?

2024-06-06 12:30 UTC, caugner commented on kumascript/src/lib/css-syntax.ts
> +          /\]([^']?)$/,
As discussed, this change avoids the linking of the literal `]`, just the diff is outdated.

2024-06-06 12:39 UTC, caugner commented on kumascript/src/lib/css-syntax.ts
> +      spec_values = spec_values.filter(({ spec }) => !/-\d+$/.test(spec));
```suggestion
      // Filter out specs that end "-n" where n is a number.
      spec_values = spec_values.filter(({ spec }) => !/-\d+$/.test(spec));
```

2024-06-06 12:40 UTC, caugner approved these changes

2024-06-06 20:10 UTC, merged