chore(translate):side menu for add section and translate section
mdn/yari pull request #11152
Opened 2024-05-18 04:45 UTC by gurezo

## Summary
@hmatrjp @potappo , mdn-yari-ja

please review for this pull request

- issue:  [ サイドメニュー の翻訳（Games — Developing games for the web, Guides and tutorials） #760 ](https://github.com/mozilla-japan/translation/issues/760) 

### Problem
still en-us only

#### English
![スクリーンショット 2024-05-18 13 26 31](https://github.com/mdn/yari/assets/7631567/2dbcd15d-c29e-432b-bb9b-121003adb160)

#### Japanese
![スクリーンショット 2024-05-18 13 26 58](https://github.com/mdn/yari/assets/7631567/3e20144b-9b78-48d6-ba92-72d64a78aaf1)

### Solution

translate japanese for LearnSidebar.ejs

### NOTICE

@caugner, @wbamberg , @schalkneethling 

Please merge once mdn-yari-ja is approved.

### Before

still en-us only

### After

add tranlate japanese for LearnSidebar.ejs

2024-05-18 05:24 UTC, potappo requested changes
Web はウェブでお願いします。

2024-05-18 05:33 UTC, gurezo commented
@potappo 

> Web はウェブでお願いします。

修正しました！
[6cb40d8](https://github.com/mdn/yari/pull/11152/commits/6cb40d894436648f1c3c56d98088d57800228c92)

2024-05-18 05:37 UTC, potappo approved these changes
LGTM, Thanks!

2024-05-18 05:40 UTC, gurezo commented
@caugner, @wbamberg , @schalkneethling

already approved by mdn-yari-ja (@potappo )
please this PR review

2024-05-20 13:46 UTC, caugner approved these changes

2024-05-20 13:46 UTC, merged