[DON'T MERGE YET] Update Observatory links in HTTPsidebar
mdn/yari pull request #11236
Opened 2024-06-03 11:18 UTC by chrisdavidmills

## Summary

In https://github.com/mdn/content/pull/33793, I am adding the security docs that accompany Mozilla Observatory to MDN. I noticed that after this work is merged and Observatory is moved over to MDN, the HTTP docs sidebar will then contain out-of-date links.

This PR fixes that sidebar to link to the correct new locations of the Observatory tool and associated docs.

This shouldn't be merged until the above two items are done.

### Problem

### Solution

---

## Screenshots

### Before

### After

---

## How did you test this change?

2024-06-14 22:54 UTC, caugner requested changes
The changes don't look right, as if a VSCode extension reformatted the file in a weird way. This not only makes it hard to review the changes, but appears to have caused syntax errors that cause the tests to fail. Can you please take a look?

PS: Afaik there is no formatter for EJS, so you might have to reset and start from scratch.

2024-06-17 13:11 UTC, chrisdavidmills commented
> The changes don't look right, as if a VSCode extension reformatted the file in a weird way. This not only makes it hard to review the changes, but appears to have caused syntax errors that cause the tests to fail. Can you please take a look?
> 
> PS: Afaik there is no formatter for EJS, so you might have to reset and start from scratch.

@caugner ah man, that really sucks. I didn't even notice it had done that. I will have another go at this tomorrow.

2024-06-21 13:52 UTC, caugner approved these changes

2024-06-21 14:10 UTC, caugner commented
@chrisdavidmills Fixed the PR, and added screenshots. Will merge this into the `observatory` branch now.

2024-06-21 14:10 UTC, merged