rename tool commands
mdn/yari pull request #1554
Opened 2020-10-28 13:57 UTC by fiji-flo

2020-10-28 15:27 UTC, escattone commented on docs/cli-tool.md
> +Run the cli tool:
Nit:
```suggestion
Run the CLI tool:
```

2020-10-28 15:27 UTC, escattone commented on docs/cli-tool.md
> +  cli.js 0.0.0
Does `caporal` have a way to use a different name than the one from the command line? It'd be nice to use `tool` (or whatever else we decide) instead.

2020-10-28 16:19 UTC, escattone approved these changes
This looks great to me, thanks @fiji-flo. We can decide later if we want to change `tool` to something else.

2020-10-29 12:24 UTC, peterbe requested changes

2020-10-29 12:24 UTC, peterbe commented on docs/cli-tool.md
> +                                         messages.
That's just bound to become out of date :)
Perhaps it's enough to say:

    Run the CLI tool:

    ```sh
    yarn tool --help
    ```

2020-10-29 12:24 UTC, peterbe commented on docs/cli-tool.md
> +### validate-redirect
Don't hate me for suggesting this but shouldn't be called `validate-redirects`?

2020-10-29 12:24 UTC, peterbe commented on docs/cli-tool.md
> +### crate
```suggestion
### create
```

2020-10-29 12:24 UTC, peterbe commented on docs/cli-tool.md
> +environment variable).
This is for the `edit` command.

2020-10-29 12:24 UTC, peterbe commented on docs/cli-tool.md
> +Open a document by its slug in the preferred editor (as per the EDITOR
```suggestion
Open a document by its slug in the preferred editor (as per the `EDITOR`
```

2020-10-29 12:24 UTC, peterbe commented on docs/cli-tool.md
> +redirect if deleting a single document. Also stages changes in git (except for
```suggestion
redirect if deleting a single document. Also stages changes in `git` (except for
```

2020-10-29 12:24 UTC, peterbe commented on docs/cli-tool.md
> +Spawn a preview of a given slug in your browser. This depends on a running
I don't know what "spawn a preview" means. Perhaps it should have been called `open`.

2020-10-29 12:25 UTC, peterbe commented on docs/cli-tool.md
> +Install dependencies:
I don't think this belongs.

2020-10-29 12:56 UTC, fiji-flo commented
I addressed all comments.

2020-10-29 12:57 UTC, peterbe approved these changes

2020-10-29 12:59 UTC, merged