allow turning of file watching
mdn/yari pull request #1687
Opened 2020-11-10 15:20 UTC by fiji-flo

- add REACT_APP_NO_WATCHER to disable file watching
- resolves #835

2020-11-10 18:52 UTC, peterbe commented
I'd rather we mention the problem in README to help you fix the problem if you actually want the watcher on Linux. 
Once that's in place, this PR makes more sense.

2020-11-10 18:52 UTC, peterbe commented
I guess I'm saying that based on the fact that this PR's description resolves #835

2020-11-10 19:07 UTC, Ryuno-Ki commented
I'm absolutely fine with disabling the watcher on my Linux and trigger a new build if needed. Thanks for also documenting it.

2020-11-10 19:14 UTC, peterbe commented
> I'm absolutely fine with disabling the watcher on my Linux and trigger a new build if needed. Thanks for also documenting it.

We should have both: A guide/help for people who want to enable it and an option to disable the watcher.

2020-11-11 16:25 UTC, peterbe commented on client/src/constants.ts
> +  process.env.REACT_APP_NO_WATCHER || "false"
This also needs to be mentioned in [`docs/envvars.md`](https://github.com/mdn/yari/blob/master/docs/envvars.md#client).

2020-11-11 16:25 UTC, peterbe commented on client/src/constants.ts
> +  process.env.REACT_APP_NO_WATCHER || "false"
Bah! Ignore me. I read this PR wrong.

2020-11-17 13:16 UTC, peterbe requested changes
I haven't finished reviewing it but some early feedback already is that the Document Spy should become aware of the `process.env.REACT_APP_NO_WATCHER` variable so it can say something like "Not actively watching for file changes"
Or, perhaps just show absolutely nothing. What do you think?

2020-11-17 13:16 UTC, peterbe commented on README.md
> +1. Disable the watcher via [`REACT_APP_NOW_WATCHER`](docs/envvars.md#react_app_no_watcher)
```suggestion
1. Disable the watcher via [`REACT_APP_NO_WATCHER`](docs/envvars.md#react_app_no_watcher)
```

2020-11-17 13:16 UTC, peterbe commented on README.md
> +### Error: ENOSPC: System limit for number of file watchers reached
```suggestion
### `Error: ENOSPC: System limit for number of file watchers reached`
```
to make it monospace.

2020-11-17 13:26 UTC, peterbe reviewed
The `<Document/>` gets its content from a `useSWR` hook. Every time the WebSocket tells the Document Spy that the file changed on the file system it triggers the `mutate()` function (see `client/src/document/index.tsx`)
But `useSWR` also has the ability to automatically refresh itself every time you focus the browser page (thanks to the PageVisibility API). This feature gets disable on the hook because the Document Spy is better. But if someone opts to disable the file watcher, I think it should be enabled. 

In that same index.tsx replace:

```diff
-  revalidateOnFocus: false,
+ revalidateOnFocus: !!process.env.REACT_APP_NO_WATCHER,
```

That way, for people who have disabled their file watcher, to refresh content all they need to do is to switch out of the browser and switch back into it. It's pretty smooth. I tested it.

2020-11-17 13:26 UTC, peterbe commented on README.md
> +   export REACT_APP_NO_WATCHER=true
THis doesn't wrap as a code block FYI.

2020-11-17 14:00 UTC, peterbe requested changes
The thing I really don't like is that the `REACT_APP_NO_WATCHER` in invoked long before the lines that are troubling. What really causes a problem is:
```javascript
const watcher = chokidar.watch(...);
```
...which happens as soon as `document-watch.worker.js` is initialized by `worker_threads`. 
You can send options to the constructor of `Worker` so that the `document-watch.worker.js` would be informed to not start `chokidar.watch()` and instead do your own `glob.sync()` thing there. That way, you can move all the logic for *creating* the search index all in a worker thread for both those with and those without `REACT_APP_NO_WATCHER`. And then you can use all the same routines for adding to the search index. That way we don't need to maintain two separate almost identical blocks of code for adding to the `searchIndex`. 

I note, that the `glob.sync` takes almost 2 seconds on my machine and that would be nice to move to a worker thread.

2020-12-01 22:15 UTC, peterbe commented
My pseudo passive aggressive form of code review is to redirect it back to you to review half of your own code over at: https://github.com/mdn/yari/pull/1901
I'm hoping that helping you with this will free up your mind to focus on the unfreezing locales project :)

2020-12-02 14:10 UTC, fiji-flo commented
fixed via #1901

2020-12-02 14:10 UTC, closed without merging