do not mutate the doc.url
mdn/yari pull request #1754
Opened 2020-11-17 18:42 UTC by fiji-flo

fixes #1709
Nasty to debug. We mutated a memoized object.

2020-11-17 20:13 UTC, peterbe commented on content/document.js
> +    return { url: `${doc.url}#${hash}`, ...doc };
I don't know why but I don't understand this. If you want to NOT mutate but to create a copied object, but with a different `url` key, then normally you do:
```javascript
const foo = { url: "something", other: "stuff" };
console.log({ url: "new", ...foo });
```
will output:
```
{ url: 'something', other: 'stuff' }
```

But I appreciate the underlying core problem. You get a memorized thing back from a memorizing function, but then you mutate it which is just wrong. So why would your PR fix the problem??

2020-11-17 20:16 UTC, peterbe commented on content/document.js
> +    return { url: `${doc.url}#${hash}`, ...doc };
Bah! I figured it out. My comment was correct. You're creating a new object the wrong way. Here's how I reproduced the problem:
```javascript
const { findByURL } = require("./content/document.js");

console.log(
  findByURL("/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords").url
);
console.log(
  findByURL("/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#other").url
);
console.log(
  findByURL("/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords").url
);
```
And when run with `NODE_ENV=production node dummy.js` it spits out:
```
/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords
/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords#other
/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords#other#keywords
```
which looks exactly like the problem we have. 
If I change to your solution the output becomes:
```
/en-US/docs/Web/JavaScript/Reference/Lexical_grammar
/en-US/docs/Web/JavaScript/Reference/Lexical_grammar
/en-US/docs/Web/JavaScript/Reference/Lexical_grammar
```
But if you create the new object clone with `url` last, the output (correctly) becomes:
```
/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords
/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#other
/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords
```

2020-11-17 20:17 UTC, peterbe commented on content/document.js
> +    return { url: `${doc.url}#${hash}`, ...doc };
```suggestion
    return { ...doc, url: `${doc.url}#${hash}` };
```

2020-11-17 20:22 UTC, peterbe requested changes
Pretty sure the suggestion edit solves the problem. I suspect it's just a humble mistake (on top of a mistake that I introduced) so once you double-check, we can approve and merge this. The "Request changes" is just a gentle reminder.

2020-11-18 09:52 UTC, fiji-flo commented
My bad, don't know what I was thinking.

2020-11-18 13:34 UTC, peterbe approved these changes

2020-11-18 13:34 UTC, merged