BCD table crashes shouldn't break the page
mdn/yari pull request #2041
Opened 2020-12-09 21:45 UTC by peterbe

Fixes #2020

@ddbeck I can't request a review from you. I added you with `Write` permission to the repo but perhaps it's pending you invitation acceptance. Or perhaps some caching going on in the PR UI. Anyway...

@schalkneethling Can you please review the appears and can you also sanity test my PR. If you open `lazy-bcd-table.tsx` you'll see that there are 3 individual chances of NOT displaying the full BCD table but instead displaying an "error message". 
Can you please have a think about some better styling we can use. Perhaps there's something from minimalist or from the `ui` folder that I can use?

@ddbeck Can you sanity check the implementation and perhaps reflect on the "word smithing" of the error message it self. Here's what it looks like:
<img width="707" alt="Screen Shot 2020-12-09 at 4 40 52 PM" src="https://user-images.githubusercontent.com/26739/101691864-5184b600-3a3d-11eb-8971-237bc32a093b.png">
It crashes hard [in stage](https://github.com/mdn/yari/issues/2020) because the sub-component shouldn't have been even attempted if the data isn't there. When open `node_modules/@mdn/browser-compat-data/api/CSSTransformComponent.json` I can clearly see that there's no entry for `toString`. I'm not judging that really. It's going to happen again sooner or later. And it can equally happen if you'd typed `{{Compat("api.CSSTransformComponent.toMatrixxxxtypo")}}` 

Whilst you guys can take a look at that I'm going to follow-up with a thing so that this is registered as a flaw. The author of that page should be made aware that `api.CSSTransformComponent.toString` doesn't exist in BCD.

2020-12-09 21:46 UTC, peterbe commented
There. EIther you accepted the invitation or it was a matter of refreshing this page but now I'm able to request a review from your @ddbeck

2020-12-09 22:24 UTC, peterbe commented
Ok, I fixed the problem with it not being flagged as a flaw. What happened was that it was seeking a property called `toString` which is not present in the bcd JSON files but it's truthy because it's a built-in prototype property. E.g.
```
> var some = {thing: 'sure'}
undefined
> if (!some.thing) { console.log('Some.thing is not there') }
undefined
> if (!some.definitelyNot) { console.log('Some.definitelyNot is not there') }
Some.definitelyNot is not there
undefined
> if (!some.toString) { console.log('Some.toString is not there') }
undefined
```
So I forced it to use `hasOwnProperty()` and that seems to solve it.

2020-12-09 22:24 UTC, peterbe commented
Helps if I follow the `eslint` rules I added to the CI :) 
https://eslint.org/docs/rules/no-prototype-builtins

2020-12-09 22:32 UTC, peterbe commented
Oh. I must have gotten something wrong. Now BCD tables aren't showing up at all :)
I'll figure it out tomorrow. I would still appreciate your review.

Note to self, see http://localhost:3000/en-US/docs/Web/CSS/transform-function/rotateY()#_flaws

2020-12-10 16:22 UTC, ddbeck requested changes

2020-12-10 16:22 UTC, ddbeck commented on client/src/document/lazy-bcd-table.tsx
> +      </p>
Cribbing a bit from the current kumascript macro text. How about something like this?

```suggestion
      <p>
        No compatibility data found for <code>{query}</code>. Check the spelling or contribute data to <a href="https://github.com/mdn/browser-compat-data">mdn/browser-compat-data</a>.
      </p>
```

2020-12-11 12:35 UTC, peterbe commented
@ddbeck I accepted your edit. r?
@schalkneethling I'm really eager to merge this because it crashes the page. If you can't think of a quick and easy `className` to add or some SCSS I can copy-n-paste, can you please r+ and file a follow-up issue?

2020-12-11 12:46 UTC, ddbeck approved these changes
Thank you!

2020-12-11 22:15 UTC, peterbe commented
@schalkneethling Since it turns out that the message is actually hidden if the BCD `query` doesn't resolve now. You actually don't even see the "error message" that Daniel and I debated. But there's an issue filed about reversing that so these error messages do become visible again. Would you mind filing a follow-up or something so we can include error messages that are appropriate for when things go wrong. It's also equally applicable for the KS macros that fail to render: https://github.com/mdn/yari/issues/1041 
So can you think up a good `className` I can use for display rendering problems?

2020-12-11 22:15 UTC, peterbe commented
But for now, I'll merge this so we don't crash on those pages at least.

2020-12-11 22:15 UTC, merged