Guard-rails when setting invalid CONTENT_*_ROOT
mdn/yari pull request #2337
Opened 2021-01-05 02:15 UTC by peterbe

Fixes #2335

Now, you'll hopefully wake up a bit more when you have a typo in either of those environment variables.

2021-01-05 02:17 UTC, peterbe commented on content/constants.js
> +  throw new Error("Env var CONTENT_ROOT must be set");
this one is kinda new and somewhat unrelated to the issue. But I realize, that `console.assert` was rather useless as it was before. There's absolutely no point carrying on if it's not set.

2021-01-06 11:04 UTC, fiji-flo approved these changes
👍

2021-01-06 11:21 UTC, fiji-flo requested changes
For some reason this breaks CI. Looks like `dotenv` (possibly the relative path) isn't working.

2021-01-06 15:19 UTC, peterbe commented
@fiji-flo tests should be passing now.

2021-01-06 16:07 UTC, fiji-flo approved these changes
Cool

2021-01-06 16:07 UTC, merged