Add more descriptive tooltip for <= versions
mdn/yari pull request #2966
Opened 2021-02-17 20:25 UTC by cincodenada

The existing tooltip can easily be read as implying the feature is only supported in the given range, rather than support starting in that range. It's doubly confusing when the removed version is <=, because then the tooltip is written primarily for the added case.

I haven't yet set up a whole environment so this is untested, but I wanted to open it as a suggestion to see if it there was interest, to make sure it was worth investing the time to get an environment set up to compile it locally and all.

I considered creating an enum rather than `'added'`/`'removed'` magic string values, or just having a boolean e.g. `isAdded`, so I'm open to suggestions on how to communicate the difference between those cases.

2021-02-17 20:43 UTC, mattiapontonio commented
Unfortunately I can't see the mobile tooltip.
And I don't even see:
-  removed version
- added version

![Screenshot_20210217-213903.png](https://user-images.githubusercontent.com/44380480/108265177-b872c980-7168-11eb-8acf-abbcaa153e6a.png)

2021-02-17 21:01 UTC, mattiapontonio commented
To be explicit, the tooltip will probably have to be removed because it cannot be seen from mobile and because it is better to find a visible arrangement of data such as a table so in my opinion it is not worth investing in the tooltip.

2021-02-17 21:04 UTC, peterbe commented
@cincodenada You did all of that using the GitHub UI?! Cool. 
You should really try to check out the project locally. It's easy. At least it should be. And if it isn't, perhaps someone of your caliber can help us improve the README to make it easy/easier to check out the project locally. 

@ddbeck or @Elchi3 Can you provide some early/quick feedback to @cincodenada about the underlying feature here? If it helps, I can vet the code and perhaps run it to present some screenshots for an easier discussion.

2021-02-17 21:26 UTC, cincodenada commented
@peterbe The first commit was all in the web IDE yeah! It's pretty slick these days. When the linter checks failed I did get it checked out locally so I could run `prettier` and it was indeed pretty easy all set up. I reworked the code a bit to avoid a really nasty linebreak in the autoformatting in the `slice()`.

I just checked out the README and it was impressively easy to get up and running, I went ahead and did so, so here's before/after screenshots of `-webkit-mask-attachment`, my mouse pointer doesn't show but it's hovering over the second `≤37` in both:
<img width="1003" alt="Screen Shot 2021-02-17 at 1 19 10 PM" src="https://user-images.githubusercontent.com/479715/108269930-8be88e80-7123-11eb-8de0-711ee8bb093d.png">
<img width="1003" alt="Screen Shot 2021-02-17 at 1 23 30 PM" src="https://user-images.githubusercontent.com/479715/108269942-90ad4280-7123-11eb-8814-1f2b7899a8f0.png">

2021-02-17 21:33 UTC, cincodenada commented
As for mobile tooltips, I know there are various ways to support tooltips on mobile but am not really familiar with them beyond that, and there may be an established way in this or other MDN projects. An alternate solution would be to use something like footnotes, at least for more complicated situations like the <= case.

Also, I'm not committed to any specific wording here - for instance, "Exact version unknown" may be more verbose than necessary, re-reading it now perhaps "Specific version" would be more precise. Happy to hear any feedback on the wording too.

2021-02-17 21:52 UTC, mattiapontonio commented
Sorry I didn't understand that it was the `title`, I thought it was a custom tooltip.

2021-02-17 22:00 UTC, mattiapontonio commented
> support tooltips on mobile

It doesn't matter for now, title is fine. 👍
We just don't buy anything, we put an element for everything we have in the house with the relative title.
IMHO

2021-02-17 22:15 UTC, mattiapontonio commented
FTR
https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#the-support-object

2021-02-17 22:30 UTC, cincodenada commented
I didn't understand how it worked at first, and in fact got an incorrect idea of how the <= worked from reading the tooltips, which is why I'm here :)

I got some very helpful explanation from some folks from commenting on the browser-compat-data PR that introduced the <= version that I saw, which is how I understand now, it may be helpful context: https://github.com/mdn/browser-compat-data/pull/4637

Of particular note is the "Ranged versions" section of the docs linked above, which explains specifically what <= means: https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#ranged-versions

2021-02-17 22:40 UTC, mattiapontonio commented
```HTML
<div title="Prefix">{prefix}</div>
<div title="Version added">{version_added}</div>
<div title="Version removed">{version_removed}</div>
<div title="Alternative name">{alternative_name}</div>
<div title="Flags">{flags}</div>
<div title="Partial implementation">{partial_implementation}</div>
<div title="Notes">{notes}</div>
```

_simple_support_statement_

The problem is that if you criticize browsers-compact-data here at Yari you risk big because @chrisdavidmills scolds you. So I recommend that you map them all in the cell without thinking too much. Apparently the data structure is already ok as it is.

I'm playing a bit but I'm pretty serious about the code, it's better to map the object.

2021-02-18 02:13 UTC, mattiapontonio commented
I have an idea for the notes. we could put 3 buttons with an exclamation mark that alert the notes so we do the JavaScript inline and it works on mobile.

2021-02-18 06:29 UTC, cincodenada commented
I am not at all criticizing browsers-compact-data here - in fact, my assertion is that as-is the chart is misrepresenting the data they provide. For instance, for both `version_removed: "<=37"` (meaning support was removed in some unknown version up to or including 37) and `version_added: "<=37"` (meaning support was added in some unknown version up to or including 37), the tooltip we show says "Supported in version 37 or earlier", which I don't think clearly describes either situation.

The existing code is already calculating that sentence for the tooltip - this PR is just changing the sentence to more accurately reflect the data provided by browsers-compat. And we already take into account all the items in `support_structure` - we represent notes, flags, prefix, alternative_name, partial implementations, and added/removed versions, each in appropriate ways in the given table. Many of these members are optional and absent in most cases, so having a bunch of empty cells would be a waste of space.

And in any case, the issue at hand is that the sentence we calculate for a specific type of added/removed version (the <= version) doesn't fully describe the meaning that browsers-compat specifies for it, and can be easily misinterpreted so as to not represent the intent of browsers-compat. This PR updates how we calculate the sentence to better reflect the intent of browsers-compat.

2021-02-18 08:13 UTC, Ryuno-Ki commented
@cincodenada #2705 is talking about accessible tooltips, so don't worry about it right now.
Thanks for your contribution!

2021-02-18 08:34 UTC, cincodenada commented
@Ryuno-Ki Oh, excellent, thanks for the tip! I am also interested in improving tooltips separately, so I appreciate the link :)

2021-02-18 12:38 UTC, peterbe commented
@Elchi3 @ddbeck Is this something you have time to review? I'll take a look at the actual code itself but perhaps are (much) better equipped to evaluate the (more important) aspect of the actual functionality change.

2021-02-18 12:52 UTC, ddbeck commented
I'm fine with this approach to the title text, though I have a small suggestion for the phrasing (though I'm not sure how best to implement it).

In the screenshot, the final string in the ranged case is: "Specific version unknown: supported ending in version 37 or earlier." That "supported" makes it a little bit awkward to read. "Specific version unknown: support ended in version 37 or earlier." flows a little better.

Alternatively—since there many entries that use this notation—it might be better to put the more specific details first and put the general caveat last. Something like, "Support ended in version 37 or earlier (specific version unknown)"

2021-02-18 12:53 UTC, ddbeck commented
By the way, @cincodenada thanks for taking an interest in this. Glad my explanation in the compat repo was helpful!

2021-02-18 13:24 UTC, peterbe approved these changes
@cincodenada If you can heed Daniel's suggestions I'm ready willing and able to merge this. Great work! We need more people like you.

2021-02-19 18:00 UTC, cincodenada commented
Great, thanks for all the feedback! I've updated the wording per @ddbeck's suggestions, which I think are all good improvements.

All good to merge from my end. One final bit of bikeshedding I realized: with the new wording, we could also just use browser-compat-data's wording directly and say "Support added"/"Support removed" (vs started/ended). If that seems markedly better I can make that change as well.

2021-02-22 12:55 UTC, ddbeck commented
Great! I don't think we need to exactly follow the wording from BCD. Maybe continue with the wording you've got here and revisit it if there's confusion about the tooltip text?

@peterbe I'm happy with this, but I'll leave actual code review to you.

2021-02-22 13:25 UTC, peterbe requested changes
The use of a string as a form of "enum" is a bit strange when there's only ever two possible states. Can you change the signature to:

```javascript
function labelFromString(
  version: string | boolean | null | undefined,
  added: bool
) 
```
And where you call it, change according to: `labelFromString(added, true)` or `labelFromString(removed, false)`.

What's cool about TypeScript is that it you give you a nice tooltip in your IDE when you hover over the `labelFromString` and then it's not so weird to know/see/remember what that second boolean is for. 

Another syntax which is quite nice would be something like this:

```javascript
function labelFromString(
  removed?: string | boolean | null | undefined,
  added?: string | boolean | null | undefined,
) 
```
then you can use it like this, for example:
```javascript
labelFromString({ removed })
```
and within the function you'd be able to tell which description to use based on the argument used. 

For I think the first suggestion is simpler and more appropriate. A bool instead of a string enum.

2021-02-27 05:21 UTC, cincodenada commented
I had considered the boolean option, so I'm happy to go with that - I took a slightly different tack and made it an optional boolean, essentially defaulting to the added case, since removed is the minority/exceptional case. That said, if there's a preference for explicitly including the second argument in both cases, I'm fine with going that way as well.

The property shorthand idea is quite clever indeed, and rather elegant! I also agree it may be just a bit _too_ clever, as much as I love it, and the simpler boolean is the way forward :)

2021-03-01 13:18 UTC, peterbe approved these changes

2021-03-01 13:19 UTC, peterbe commented
@cincodenada Same problem here. I can't seem to override the fact that your commits aren't signed. Do you mind rebasing your branch locally so all commits are signed?

2021-04-03 21:32 UTC, cincodenada commented
Okay, as on the other one, finally got around to this and rebased/squashed a bit while I was at it. Let me know if there's any remaining feedback, thanks!

2021-04-14 15:22 UTC, Ryuno-Ki reviewed
Some nits (but there would be merge conflicts anyway).

2021-04-14 15:22 UTC, Ryuno-Ki commented on client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
> +  version: string | boolean | null | undefined,
Is there a difference between the above and
```suggestion
  version?: string | boolean | null,
```
?

2021-04-14 15:22 UTC, Ryuno-Ki commented on client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
> +  const versionDescription = `version ${version.slice(1)} or earlier`;
Assuming `version` has a value of `≤ 79` there would be a doubled space here.
Is it guaranteed to be in shape of `≤79`?
(79 being a random number)

2021-04-14 15:22 UTC, Ryuno-Ki commented on client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
>        <sup>≤&#xA0;</sup>
```suggestion
      <sup>≤<NonBreakingSpace /></sup>
```
(for readability)

2021-04-14 17:12 UTC, Elchi3 commented
In https://github.com/mdn/yari/issues/3238 a proposal was made to hide the "≤" annotation altogether to avoid confusion and we came to agreement there, so I think this PR should be closed. Thanks for your work, though!

2021-04-15 20:35 UTC, escattone commented
Closing, but thanks for all of your work on this @cincodenada!

2021-04-15 20:35 UTC, closed without merging

2021-04-15 21:55 UTC, cincodenada commented
Oh, yeah reading up on #3238 I agree that is the better solution overall, the <= doesn't really add much information in this context, so if we can just clear up the confusion by leaving it out I'm all for it!

Thanks for looping back here and for all the feedback in the process all the same :)

2021-04-16 06:08 UTC, Elchi3 commented
Thanks @cincodenada! Your work definitely also helped us to realize what is best 👍