smartlink to fallback on en-US
mdn/yari pull request #3133
Opened 2021-03-04 17:28 UTC by peterbe

Fixes #3053

Before (http://localhost:3000/ca/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse):
<img width="938" alt="Screen Shot 2021-03-04 at 12 25 56 PM" src="https://user-images.githubusercontent.com/26739/110003987-f0d7e300-7ce4-11eb-8de9-364081599d95.png">

After:
<img width="644" alt="Screen Shot 2021-03-04 at 12 25 35 PM" src="https://user-images.githubusercontent.com/26739/110004054-0220ef80-7ce5-11eb-8ca6-df9012be0e05.png">

Before (http://localhost:3000/de/docs/Web/CSS/Reference):
<img width="1278" alt="Screen Shot 2021-03-04 at 12 25 25 PM" src="https://user-images.githubusercontent.com/26739/110004113-11a03880-7ce5-11eb-83c2-001741ab8ceb.png">

After:
<img width="1231" alt="Screen Shot 2021-03-04 at 12 25 03 PM" src="https://user-images.githubusercontent.com/26739/110004139-182eb000-7ce5-11eb-81f1-33f33e3ebe27.png">

2021-03-04 17:30 UTC, peterbe commented
@chrisdavidmills  I basically just took [your suggestion](https://github.com/mdn/yari/issues/3053#issuecomment-789611237). 

@schalkneethling Please review my use of the `<small>` tag for the `(en-US)` portion. 

@fiji-flo Would it be better to go through the `translationsOf` Map object?

2021-03-04 17:47 UTC, fiji-flo approved these changes
❤️

2021-03-04 18:28 UTC, escattone reviewed
On my phone, so unable to test. Just a tiny nit for now.

2021-03-04 18:28 UTC, escattone commented on kumascript/src/api/web.js
> +          `${hrefpath} does not exist but fallbacked on ${enUSPage.url}`
```suggestion
          `${hrefpath} does not exist, fallback to ${enUSPage.url}`
```

2021-03-08 21:00 UTC, escattone approved these changes
Love it, looks and works great, thanks @peterbe!

2021-03-08 21:55 UTC, escattone commented
@schalkneethling I know you have a lot on your plate, but would you mind giving this a quick review for any a11y concerns, specifically regarding the use of `<small>` tag?

2021-03-09 05:06 UTC, schalkneethling requested changes
This is going to be so awesome. Thank you, Peter. Just one change recommendation.

2021-03-09 05:06 UTC, schalkneethling commented on kumascript/src/api/web.js
> +      }
```suggestion
        return (
          '<a class="page-only-in-english" ' +
          'title="Page currently only available in English" ' +
          `href="${enUSPage.url}"${flawAttribute}>${content} <span>(en-US)</span></a>`
        );
```

Then in `client/src/document/index.scss` add the following:

```
.page-only-in-english {
  span {
    font-size: $small-font-size;
  }
}
```

2021-03-09 13:26 UTC, schalkneethling commented on kumascript/src/api/web.js
> +      }
I know, sometimes I want to change my mind about the use of these elements but, we would need CSS anyhow to ensure that the `small` element uses the `$small-font-size`. I am kinda undecided on that one.

2021-03-09 13:27 UTC, schalkneethling approved these changes
🎉  - Thank you @peterbe

2021-03-09 14:12 UTC, merged