2505 account settings
mdn/yari pull request #3298
Opened 2021-03-22 13:09 UTC by schalkneethling

- fix: sign-in and sing-up page ui
- remove extra period
- fix failing tests
- remove populate-search-index-benchmark
- feedback on sign-up styling PR
- changes based on review feedback
- fix: account settings ui

2021-03-22 19:11 UTC, peterbe requested changes
@schalkneethling You flagged me for review but the sign-in-sign-up PR hasn't landed yet. And tests here are failing. 
So I don't forget and miss that the ball is in whose court, I'm going to reject this review request until you have finished this PR (i.e. merging in main and fixing the tests). Also, if you need help debugging the tests, ping me on Slack.

2021-03-23 02:57 UTC, schalkneethling commented
> @schalkneethling You flagged me for review but the sign-in-sign-up PR hasn't landed yet. And tests here are failing.
> So I don't forget and miss that the ball is in whose court, I'm going to reject this review request until you have finished this PR (i.e. merging in main and fixing the tests). Also, if you need help debugging the tests, ping me on Slack.

Yup, I fully expected some tests to fail but wanted to get this on your radar so that, should you have a spare moment, you could perhaps provide some preliminary feedback.

All good though.

2021-03-23 03:36 UTC, schalkneethling commented
@peterbe I notice that the test `should show your settings page` fails. When I run `TESTING_OPEN_BROWSER=true yarn test:testing headless` I see the last test shows the "You are not signed in" view instead of the settings page.

2021-03-23 14:22 UTC, peterbe approved these changes

2021-03-23 14:33 UTC, merged