add Open Graph HTML metea tags
mdn/yari pull request #3623
Opened 2021-04-23 20:58 UTC by peterbe

Fixes #3590

This adds `<meta property="og:title" content="...">`, `<meta property="og:url" content="...">`, and `<meta property="og:description" content="...">`

It [seems that](https://github.com/mdn/yari/issues/3590) Twitter won't display MDN URLs nicely unless you have the `twitter` card HTML meta tags or Open Graph HTML meta tags. 
Thankfully, it seems that Twitter will fall back to Open Graph if Twitter card tags don't exist.

2021-04-23 21:03 UTC, peterbe commented
I've also kicked off a complete build to the dev server for this branch. 
So in about 1.5h from the time of writing this, 
https://opengraph.content.dev.mdn.mozit.cloud/en-US/docs/web/Javascript will become available and we can use that to test in https://cards-dev.twitter.com/validator and https://developers.facebook.com/tools/debug/ and maybe https://www.opengraph.xyz/ whatever that is.

We should also test SPAs such as https://opengraph.content.dev.mdn.mozit.cloud/en-US/ and https://opengraph.content.dev.mdn.mozit.cloud/en-US/signin and https://opengraph.content.dev.mdn.mozit.cloud/en-US/search
And equally for all those above tests, make sure it works for some non-en-US locales too. E.g. https://opengraph.content.dev.mdn.mozit.cloud/zh-CN/signin

2021-04-23 21:03 UTC, peterbe commented
@tannerdolby r?

2021-04-23 21:04 UTC, peterbe commented
@schalkneethling @escattone would be good to get your eyes on this too.

Since we use the canonical URL in the pre-built HTML we can't get the `og:url` to match whatever domain we use to serve it from so when we run the validator it might complain that the domain in the URL is different from the domain in the `og:url` value.

2021-04-23 22:34 UTC, tannerdolby commented
@peterbe ready to start testing

2021-04-25 19:09 UTC, peterbe commented
Either that validator is incorrect/invalid or the documentation is. 
<img width="1085" alt="Screen Shot 2021-04-25 at 3 08 35 PM" src="https://user-images.githubusercontent.com/26739/116006202-1d6af580-a5d8-11eb-80a9-d59df83a9649.png">

Would you mind testing in Twitter, for real,  to see if it does make a pretty summary card.

2021-04-25 19:39 UTC, Ryuno-Ki commented
https://www.opengraph.xyz/url/https:%2F%2Fopengraph.content.dev.mdn.mozit.cloud%2Fen-US%2Fdocs%2Fweb%2FJavascript/ can parse it (and flags the description as being longer than 160 characters).

Twitter's validator matches the deployed implementation: https://twitter.com/AndreJaenisch/status/1386404385836654596

2021-04-25 20:09 UTC, tannerdolby commented
> Either that validator is incorrect/invalid or the documentation is.

I think I have to agree. I've tested each of the links you included and none of the Twitter cards render in a tweet or using the Twitter validator. They do produce a card using https://www.opengraph.xyz and render the `og:title` and `og:description` but its missing an image. The image is missing because in the HTML, there isn't a `<meta name="og:image" content="some-source.jpg">`, once this is added, the image should render. I'm curious to see if the Twitter validator picks it up once the `og:image` and `og:image:alt` tags are added (for some odd reason maybe requiring "all" valid Open Graph tags for it to be validated?)

We could add [this image](https://hacks.mozilla.org/files/2020/10/mdn-web-docs-vector-logo.png), which is the mozilla hacks social share image for now, its a generic “MDN Web Docs” image which works great for home pages/sign-in and should work for SPAs too. It's a really nice looking MDN Web Docs vector image which would suffice until more "customized" social share images are created for the SPAs later on.

```
<meta property="og:image" content="https://hacks.mozilla.org/files/2020/10/mdn-web-docs-vector-logo.png">
```

Manual Card Validator Tests:

1. https://opengraph.content.dev.mdn.mozit.cloud/en-US/docs/web/Javascript
   -  Using https://www.opengraph.xyz/ to validate, renders a card for each social site, but is missing an image.
   - Using twitter validator, unable to render card
    ```
    INFO:  Page fetched successfully
    INFO:  11 metatags were found
    ERROR: No card found (Card error)
    ```
   - renders as a plain link when doing a test tweet

2. https://opengraph.content.dev.mdn.mozit.cloud/en-US/ (SPA)
  -  Using https://www.opengraph.xyz/ to validate, renders a card for each social site, but is missing an image.
  - Unable to render card with twitter validator
     ```
    INFO:  Page fetched successfully
    INFO:  10 metatags were found
    ERROR: No card found (Card error)
    ```

2021-04-25 20:40 UTC, tannerdolby requested changes

2021-04-25 20:40 UTC, tannerdolby commented on client/public/index.html
> +
The `og:image` and `og:image:alt` default tags are missing to formulate a social share image for the card.

We could add the generic MDN Web Docs [vector image](https://hacks.mozilla.org/files/2020/10/mdn-web-docs-vector-logo.png) from mozilla hacks document metadata that looks really nice for now. Using `<meta name="og:image:alt">` tag would be nice too, but mozilla hacks pages don't currently use one.

```html
<meta property="og:image" content="https://hacks.mozilla.org/files/2020/10/mdn-web-docs-vector-logo.png">
```

If the [image](https://hacks.mozilla.org/files/2020/10/mdn-web-docs-vector-logo.png) exists somewhere in Yari, we could replace the `content` with a Yari URL like https://developer.mozilla.org.

2021-04-25 20:40 UTC, tannerdolby commented on ssr/render.js
Render the social share image `<meta property="og:image" content="">` meta tag.

```js
// either create a variable somewhere in render.js to store the URL 
// or place it directly in the `value` param of `.attr`
const imageUrl = "https://hacks.mozilla.org/files/2020/10/mdn-web-docs-vector-logo.png";
$('meta[property="og:image"]').attr("content", imageUrl);
```

2021-04-25 20:40 UTC, tannerdolby commented on testing/tests/index.test.js
Add a test for the `<meta name="og:image">` tag.

```js
expect($('meta[property="og:image"]').attr("content")).toBe(
   "https://hacks.mozilla.org/files/2020/10/mdn-web-docs-vector-logo.png"
);
```

2021-04-25 20:40 UTC, tannerdolby commented on testing/tests/index.test.js
> +  );
Maybe add a `<meta name="og:image">` test for the French foo page (if needed).

```js
expect($('meta[property="og:image"]').attr("content")).toBe(
   "https://hacks.mozilla.org/files/2020/10/mdn-web-docs-vector-logo.png"
);
``

2021-04-26 16:49 UTC, tannerdolby commented
@peterbe Correct, with only the the `og:title|url|description|` meta tags, the Twitter summary card fails to render using the validator and when trying to include a URL in a tweet. 

Using the opengraph.xyz site the URLs rendered a title & desc for each social sites card but all were missing an image since the `<meta name="og:image">` tag is missing in the HTML. It honestly seems that the twitter card docs aren't 100% accurate anymore, because I was able to reproduce this issue twice (once here and on my website) where the Open Graph cards aren't able to render a Twitter card at all if the `twitter:card|site|image|*` aren't around.

2021-04-27 19:07 UTC, peterbe commented
Crap! :)
It's a shame. I'm upset that Twitter can't use the `og:*` tags. 
But perhaps c'est la vie. 

But I'm tempted to pause here and land this as is. At least it's nice that we now have the correct Open Graph tags. Shame it can't work for Twitter. 
Perhaps if we can land this then we can shortly follow up with a PR to add the Twitter tags too.

2021-04-27 19:07 UTC, peterbe commented
@Gregoor See my latest comment ^. r?

2021-04-27 19:31 UTC, peterbe commented
@tannerdolby Inspired by skimming [this blog post](https://www.matuzo.at/blog/html-boilerplate/) I see that they only add `<meta name="twitter:card" content="summary_large_image">`
Now that one might not be an option for us because we don't even have a `og:image` (or `og:image:alt`) but could it be that if we add `<meta name="twitter:card" content="summary">` *then* Twitter can make do with the `og:*` meta tags?? Perhaps worth testing. ...once this PR lands.

2021-04-27 19:53 UTC, tannerdolby commented
> But I'm tempted to pause here and land this as is. At least it's nice that we now have the correct Open Graph tags. Shame it can't work for Twitter.

@peterbe Right? It is a shame that Twitter can't use the `og:*` tags. It's nice to have the Open Graph tags for now and we can resolve the twitter tags in the future.

2021-04-27 19:55 UTC, tannerdolby commented
> Inspired by skimming this blog post I see that they only add <meta name="twitter:card" content="summary_large_image".... but could it be that if we add <meta name="twitter:card" content="summary"> then Twitter can make do with the og:* meta tags??

That is a good question. I hadn't tested locally whether having the `twitter:card` tag would allow the validator to fallback to the `og:*` tags and form a pretty card. The `twitter:card` tag determines the [social cards layout](https://github.com/mdn/yari/issues/3590#issuecomment-824549765) so maybe having that is a pre-req to allowing the fallback `og:*` tags to work.

I will do some testing locally, and then test here when the PR lands. I'm curious to see what the outcome is.

2021-04-28 16:07 UTC, schalkneethling commented
Thank you for this @peterbe. In my experience, to get all of the socials(especially Twitter) to play along you need this in the `head`

```html
<meta property="og:type" content="website" />
    <meta property="og:site_name" content="MDN Web Docs" />
    <meta property="og:title" content="JavaScript forEach" />
    <meta property="og:description"
        content="Some description for the page that is less that 160 characters" />
    <meta property="og:locale" content="en-US" />
    <meta property="og:url" content="https://developer.mozilla.org/" />
    <meta property="og:image"
        content="https://developer.mozilla.org/social-banner.png" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:alt"
        content="Alt text for the image should it fail to load and for a11y." />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="MDN Web Docs" />
    <meta name="twitter:creator" content="Mozilla" />
    <meta name="twitter:title" content="JavaScript forEach" />
    <meta name="twitter:description"
        content="Some description for the page that is less that 160 characters" />
    <meta name="twitter:image"
        content="https://developer.mozilla.org/social-banner.png" />
    <meta name="twitter:image:alt"
        content="Alt text for the image should it fail to load and for a11y." />
```

2021-04-28 17:05 UTC, tannerdolby commented
@schalkneethling I agree, if the twitter meta tags are added to document metadata in the `<head>`, a nice summary card will render. I proposed adding the `twitter:*` meta tags earlier in the discussion but I think Peter was aiming to use the Open Graph tags as the fallback (and not include `<meta name="twitter*">`) tags for the twitter card when the validator tries to process the metadata. We tried that since the Twitter docs mentioned it but doesn't seem to work. 

Might try added a twitter card type like mentioned 

> but could it be that if we add <meta name="twitter:card" content="summary"> then Twitter can make do with the og:* meta tags?

but ultimately I think the `<meta name="twitter:*">` tags have to be included in document metadata for the twitter card to render nicely.

2021-04-28 19:25 UTC, peterbe commented
Plan:

1. Land this (hi @Gregoor !)
2. Experiment with adding only the `<meta name="twitter:card" content="summary">` tag to see if Twitter can then finally fall back on the Open Graph tags. 
3. Add all the relevant `twitter:*` meta tags.

2021-05-03 08:24 UTC, Gregoor commented
Looks good so far, but an image would probably be nice. I really like the social images Github started generating recently for their previews, e.g. https://twitter.com/_josh_meyer_/status/1371613146717245444
But this is a lot more effort (also many design questions) so this is not at all meant to be a recommendation for this PR.

2021-05-03 09:52 UTC, schalkneethling commented
We could use something like this, which is similar to the one BCD uses:

![MDN Web Docs social share image showing the MDN Web Docs logo and various browser logos in the background](https://user-images.githubusercontent.com/10350960/116863002-eb741780-ac05-11eb-8842-f5e73661c028.png)

2021-05-03 09:57 UTC, schalkneethling commented
Also, I tried using just `<meta name="twitter:card" content="summary_large_image" />` on https://150daysofhtml.com/ and it seems like Twitter does indeed fall back to the `og:*` tags:

![Screenshot 2021-05-03 at 11 56 58](https://user-images.githubusercontent.com/10350960/116863489-abf9fb00-ac06-11eb-8554-f24ac4f902f6.png)

2021-05-03 17:09 UTC, tannerdolby commented
> Inspired by skimming this blog post I see that they only add <meta name="twitter:card" content="summary_large_image".... but could it be that if we add then Twitter can make do with the og:* meta tags??

@peterbe It seems that you were right! Adding the `twitter:card` meta tag allows Twitter to fallback to the `og:*` tags as expected. Updated my PR review.

2021-05-03 20:18 UTC, peterbe commented
> It seems that you were right. Adding the `twitter:card` meta tag allows Twitter to fallback to the `og:*` tags as expected. Confirmed by Schalk above and I tested this locally. Updated my PR review.

What did you update? What's your current verdict on this PR?

I think the plan is still as follows:

1. Land this without worrying about Twitter or `og:image` at all for now. Just these Open Graph meta tags
2. FIgure out a good logo image to use for the `og:image` meta tag
3. Create a new PR that introduces `og:image` (and `twitter:card`) with the new image we're going to use. 

If you agree with that plan, the ball's in @Gregoor 's court right now.

2021-05-03 20:30 UTC, tannerdolby commented
I just updated [my comment](https://github.com/mdn/yari/pull/3623#discussion_r619871266) in the PR review (but probably can ignore since we plan to add `twitter:card` and `og:image` in a separate pull request). 

My current verdict on this PR is:
- Merge this for now without the `og:image` and handle that in another PR.
- We figured out that including the `<meta name="twitter:site" content="summary or summary_large_image">` will allow the twitter processor to correctly fallback to using the `og:*` tags, so definitely add that `<meta>` tag in this PR or a new one.
- No need to include the `twitter:image` since having the `twitter:site` tag around allows Twitter to fallback to `og:*` card.
- Figure out what image will go into the `og:image` tag.

So yes, I agree with the plan you proposed above 👍

2021-05-04 08:59 UTC, Gregoor approved these changes
No complaints, let's take it live!

2021-05-04 08:59 UTC, merged