Limit locales 3642
mdn/yari pull request #3661
Opened 2021-04-29 20:07 UTC by escattone

Part of #3642 (the full fix depends on also updating the lambda@edge functions).

2021-04-29 23:26 UTC, escattone commented
@peterbe @Gregoor I don't understand why these tests are failing.

2021-04-30 00:42 UTC, escattone commented
@peterbe @Gregoor I just discovered one thing I need to do is remove any URL's with retired locales from the `_redirects.txt` files in content and translated-content.

2021-04-30 18:05 UTC, escattone commented
> @peterbe @Gregoor I don't understand why these tests are failing.

@peterbe @Gregoor This was due to the presence of a URL with a retired locale in the content repo's `files/en-us/_redirects.txt`. All good now (see https://github.com/mdn/content/pull/4627). This ready for review.

2021-05-02 20:45 UTC, escattone commented
@pertebe @Gregoor FYI, at first I implemented the retired-locale redirects directly in the lambda function, but then thought that perhaps a better place for that functionality was in the fundamental redirects (e.g., links to retired locales would be detected as flaws). As it stand, this PR places the redirect code in the fundamental redirects, but if you simply remove the [last commit](https://github.com/mdn/yari/pull/3661/commits/6c39c1ffc61e38e807645f80e7e84571f40e4357), the placement moves back into the lambda function. So we can easily go either way, depending on what we all think is best.

2021-05-03 08:19 UTC, Gregoor commented
Using the flaws sounds like a great idea to me and the codes does cohere to me. I am a little sad that we don't have code-sharing between the client and lib's constants, but it's only incidentally the first time I am noticing it and not too related to this PR (plus you kept it in sync here), so that's just a note on the side.
I think Peter is in a better position to give this the final greenlight, but it lgtm 👍🏼

2021-05-03 17:57 UTC, peterbe requested changes
As per discussed, we should make the unit tests for the lambda function also test this stuff at least once. E.g. `/sv-SE/docs/Foo?utm=bla`

2021-05-03 20:49 UTC, peterbe commented on deployer/aws-lambda/content-origin-request/server.test.js
> +      "/en-US/search?retiredLocale=bn&q=video"
Nice!

2021-05-03 20:52 UTC, peterbe commented on libs/fundamental-redirects/index.js
> +      return `/en-US/${
I wonder, can you do 
```
const { DEFAULT_LOCALE } = require('../constants');
...
```
plus
```suggestion
      return `/${DEFAULT_LOCALE}/${
```

2021-05-03 20:53 UTC, peterbe approved these changes

2021-05-03 20:54 UTC, escattone commented on libs/fundamental-redirects/index.js
> +      return `/en-US/${
@peterbe Will do!

2021-05-03 21:02 UTC, merged