fix fail image.js on windows
mdn/yari pull request #3732
Opened 2021-05-06 11:42 UTC by hagiwaratakayuki

take measures against path.join uses backslash separator on windows. see build/check-images.js:127

2021-05-06 18:06 UTC, peterbe commented
Can you describe the bug? Do how do you reproduce it?

2021-05-06 18:15 UTC, peterbe requested changes
I think the solution isn't there but in how you call `slugToFolder()`
You are supposed to send it a slug which is something like `Web/Foo/bar`. That's how slugs look like on any OS. 
But I see that there's the second argument `joiner = "/"` which is probably wrong. ...for Windows. 
Perhaps the solution is to edit `libs/slug-utils/index.js` like this:
```diff
diff --git a/libs/slug-utils/index.js b/libs/slug-utils/index.js
index 112d132ab..cf21e3a84 100644
--- a/libs/slug-utils/index.js
+++ b/libs/slug-utils/index.js
@@ -1,6 +1,8 @@
+const path = require("path");
+
 const sanitizeFilename = require("sanitize-filename");
 
-function slugToFolder(slug, joiner = "/") {
+function slugToFolder(slug, joiner = path.sep) {
   return (
     slug
       // We have slugs with these special characters that would be
```
Then, that function will return a folder string that is correct for the OS.

2021-05-06 19:08 UTC, hagiwaratakayuki commented
> Can you describe the bug? Do how do you reproduce it?

1.run yari  on windows
2. access  *not* en-US, perhaps the external image has already  been downloaded by the en-US equivalent. (build/check-images.js:127) like /ja/docs/orphaned/web/guide/events/orientation_and_motion_data_explained (*)

https://github.com/mdn/translated-content/blob/main/files/ja/orphaned/web/guide/events/orientation_and_motion_data_explained/index.html

*this page is translation of  /en-US/docs/web/events/detecting_device_orientation.

2021-05-06 20:26 UTC, peterbe commented
@dalexsy Sorry for bothering you with this but perhaps if you can reproduce it on your Windows, we can figure this one out together, using your computer. 

Can you git clone the mdn/translated-content and add it to your `.env` file (`CONTENT_TRANSLATED_ROOT`). 
Perhaps you already have this. If you do, can you do a `git pull` on that repo so you have the latest. 
Then after `yarn dev` can you go to <HTTP://localhost:3000/ja/docs/web/events/detecting_device_orientation>
Do you get an error?

2021-05-07 08:11 UTC, dalexsy commented
Yes, I did:
`TypeScript error in C:/Users/user/repos/mdn/yari/client/src/document/forms/form.tsx(78,7):`
`This expression is not callable.`
`Type 'DebouncedState<(doc: DocumentOutData, didSlugChange: boolean) => unknown>' has no call signatures.  TS2349`

2021-05-07 16:58 UTC, peterbe commented
Can you upgrade your repos and `yarn install` and stuff and see if https://github.com/mdn/yari/pull/3750 solved the problem?

2021-05-17 15:17 UTC, hagiwaratakayuki commented
sorry late. it works on windows

2021-05-17 15:41 UTC, closed without merging