Add Web App Manifest Application Information specification
mdn/yari pull request #3835
Opened 2021-05-20 13:11 UTC by filips123

The `categories`, `description`, `iarc_rating_id` and `screenshots` members of [Web App Manifest](https://w3c.github.io/manifest/) have been moved into new [Web App Manifest - Application Information](https://w3c.github.io/manifest-app-info/) specification.

I will also soon create a separate PR to https://github.com/mdn/content to update needed spec links.

2021-05-20 20:03 UTC, escattone requested changes

2021-05-20 20:03 UTC, escattone commented on kumascript/macros/SpecData.json
> +    "status": "NOTE"
```suggestion
    "status": "ED"
```

2021-05-20 20:09 UTC, filips123 commented
I applied requested changes, but it seems this PR does not need to be merged anymore because of mdn/content#5164.

2021-05-20 20:12 UTC, escattone commented on kumascript/macros/SpecData.json
> +    "status": "NOTE"
It seems like this is an `Editor's Draft` rather than a `Note`?

2021-05-25 09:28 UTC, Elchi3 approved these changes
Thanks! It doesn't hurt to merge this. We haven't fully transitioned away from this file yet.

2021-05-26 00:17 UTC, escattone approved these changes

2021-05-26 00:17 UTC, escattone commented
Thanks @Elchi3!

2021-05-26 00:17 UTC, merged