Use event.key instead of event.code for detecting ”/”
mdn/yari pull request #4720
Opened 2021-09-26 22:50 UTC by claudepache

Fixes #4719

2021-09-27 09:52 UTC, bpierre commented
@claudepache Thanks! It will also probably fix this issue I opened yesterday: https://github.com/mdn/yari/issues/4718

2021-09-27 11:05 UTC, claudepache commented
> @claudepache Thanks! It will also probably fix this issue I opened yesterday: #4718

Yes. But after carefully reading your issue #4718, I realise that there is another problem with the current JS code: The search field is focused not only by pressing `/`, but also by pressing `^/` or `⌘/`, potentially hijacking keyboard shortcuts set by the browser or the user.

I will add another commit that fixes it: checking that [event.ctrlKey](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/ctrlKey) and [event.metaKey](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey) are both `false`.

2021-09-27 18:05 UTC, claudepache commented
Ok, I’ve added protections against hijacking keyboard shortcuts that include either `Ctrl` or `Meta` (which is `Command ⌘` on Mac). To keep it simple, I’ve ignored issues with other modifiers:

* The case of `Alt` is tricky: On the one hand, it is reasonable for `Alt-/` to represent some key shortcut on some platforms. On the other hand, on Mac, `Alt` (aka. `Option ⌥`) is used to produce various characters (e.g., `⌥E` outputs “€” on several layouts), and I’ve found some non-Latin Mac keyboard layouts using that modifier to produce “/”. 

* There is also the case of `AltGr` on Windows, which is detected as `Alt` + `Ctrl` (e.g., `AltGr-E` outputs “€” on several layouts). I have no idea whether `AltGr` is used to output ”/” on any keyboard layout. If it is the case, we might consider adding some test detecting `AltGr`.

* And, of course, there are other [more exotic modifiers](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/getModifierState).

2021-10-04 22:06 UTC, escattone requested changes

2021-10-04 22:06 UTC, escattone commented on client/src/search-utils.ts
> +        event.key === "/" && !event.ctrlKey && !event.metaKey &&
To satisfy prettier:
```suggestion
        event.key === "/" &&
        !event.ctrlKey &&
        !event.metaKey &&
```

2021-10-04 22:08 UTC, escattone approved these changes
Looks and works great, thanks so much @claudepache (and @bpierre for your issue as well)!

2021-10-04 22:10 UTC, merged