Use dinocon symbol for experimental support
mdn/yari pull request #5611
Opened 2022-03-14 16:28 UTC by danielhjacobs

## Summary

Fixes #5588

### Problem

The old experimental icon was the dinocon, and the new asset is harder to see in certain parts of the website.

### Solution

Copy-paste the dinocon to replace the svg.

---

## Screenshots

### Before

![Screenshot from 2022-03-14 12-24-41](https://user-images.githubusercontent.com/29206584/158217089-a5ee9f8d-5903-4e3d-904e-d7f8e60b7b1b.png)
![Screenshot from 2022-03-14 12-21-53](https://user-images.githubusercontent.com/29206584/158217090-3524e204-f0a3-44d1-acaa-358ce149e940.png)
![Screenshot from 2022-03-14 12-21-27](https://user-images.githubusercontent.com/29206584/158217092-77a4e1fb-4a48-4edb-aacc-0a5ce45ff2a5.png)

### After

![Screenshot from 2022-03-14 12-26-18](https://user-images.githubusercontent.com/29206584/158217126-f5772dde-43ce-4354-ab6c-e06e63418656.png)
![Screenshot from 2022-03-14 12-26-11](https://user-images.githubusercontent.com/29206584/158217127-4319136b-0c48-4719-b32c-53ab5a6737ca.png)
![Screenshot from 2022-03-14 12-25-35](https://user-images.githubusercontent.com/29206584/158217128-18f55851-430e-4254-b605-abe344ec9dc1.png)

2022-03-14 18:12 UTC, caugner approved these changes
LGTM, tested [locally on this article](http://localhost:3000/en-US/docs/Web/API/Window/cancelIdleCallback):

![image](https://user-images.githubusercontent.com/495429/158234569-95a1c8f4-f15c-4c85-ba6b-6f710e5cd37c.png)

I will request an additional review from a peer though.

PS: I believe we have a content issue here though, because the sidebar shows experimental for `cancelAnimationFrame`, whereas the BCD table shows experimental for `cancelIdleCallback`.

2022-03-15 09:19 UTC, schalkneethling requested changes
One change request. Other than that, this is a great change. Thanks, @danielhjacobs 🎉

2022-03-15 09:19 UTC, schalkneethling commented on client/src/assets/icons/experimental.svg
> +<svg class="icon" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img"><path d="M90.72 82.34c4.4 7 1.29 12.66-7 12.66H16.25C8 95 4.88 89.31 9.28 82.34l29.47-46.46V12
I would remove the `aria-hidden` as this icon is often used in scenarios where the explanation for the icon is shown on hover/focus. Currently we are not doing the best job of ensuring these are focusable but, not having the icon set to hidden would be a good first step.

2022-03-15 14:15 UTC, schalkneethling commented
@danielhjacobs Thank you for the change but, I see you accidentally also removed `role="img"`. We should keep that. Thanks!

2022-03-15 17:26 UTC, schalkneethling approved these changes
Thanks, @danielhjacobs! 🎉

2022-03-15 17:26 UTC, merged