chore(reference-menu): add Web Extensions item
mdn/yari pull request #5877
Opened 2022-03-31 19:16 UTC by caugner

## Summary

Fixes https://github.com/mdn/yari/issues/5876.

### Problem

The old MDN design had a "Browser extensions" item in the "Technologies" menu, but the menus of the new MDN design do not have this menu item anymore.

### Solution

Add a "Browser extensions" item to the "References" menu.

---

## Screenshots

### Before

<img width="481" alt="image" src="https://user-images.githubusercontent.com/495429/161132186-3e6ccee6-d1d9-4404-9c8a-532549988582.png">

### After

<img width="481" alt="image" src="https://user-images.githubusercontent.com/495429/161132273-4f95595c-248d-4b08-9b82-f2b57d757092.png">

---

## How did you test this change?

- Open http://localhost:3000/en-US/plus locally.

2022-03-31 19:24 UTC, caugner commented
@Rumyra Since the referenced page is still called "Browser Extensions", I have drafted this PR with these information for now:

- Title: Browser Extensions
- Subtitle: Developing extensions for web browsers
- URL: [/docs/Mozilla/Add-ons/WebExtensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions)

2022-04-01 09:44 UTC, caugner commented
Converted to draft, because this requires more discussion.

2022-04-01 15:45 UTC, caugner commented
Closing this, see: https://github.com/mdn/yari/issues/5876#issuecomment-1086057927

2022-08-17 14:23 UTC, Rumyra requested changes

2022-08-17 14:23 UTC, Rumyra commented on client/src/ui/molecules/reference-menu/index.tsx
> +        label: "Browser Extensions",
```suggestion
        label: "Web Extensions",
```

2022-08-17 14:25 UTC, dipikabh commented
For the subtitle, how about: "Extensions for web browsers" so that it's parallel in language with other subtitles?

2022-08-17 14:27 UTC, dipikabh commented
Should "Web Extensions" (new name) come after the "Web Technology" menu?

2022-08-17 14:32 UTC, Rumyra commented
> Should "Web Extensions" (new name) come after the "Web Technology" menu?

No - that's an overview page.

My suggestion is good @caugner - let's go with 'Web Extensions' 👍

2022-08-18 13:55 UTC, Rumyra approved these changes

2022-08-18 13:56 UTC, merged