Deprecate {{Tag}}
mdn/yari pull request #6269
Opened 2022-05-13 17:01 UTC by teoli2003

I'm removing the last occurrence of `{{Tag}}` in mdn/content#16006.

Let's mark it as deprecated.

2022-05-13 19:23 UTC, caugner requested changes
@teoli2003 It looks like you missed one occurrence [here](https://github.com/mdn/content/blob/485097eea7da6d9ef2b7a6c0fe68b2b00a25d3eb/files/en-us/mdn/guidelines/conventions_definitions/index.md?plain=1#L155):

```
% rg -i "\{\{ *(Tag)"
files/en-us/mdn/guidelines/conventions_definitions/index.md
155:  - If the item has any documentation pages describing only that one item (such as {{domxref("RTCPeerConnection.close()")}}), add the [`deprecated_header`](https://github.com/mdn/yari/blob/main/kumascript/macros/Deprecated_Header.ejs) macro to the top of the page and add the {{tag("Deprecated")}} tag to the page's list of tags.
```

2022-05-14 04:03 UTC, queengooborg commented
That last occurrence has now been removed, so this is ready to go!

2022-05-16 10:33 UTC, caugner approved these changes

2022-05-16 10:33 UTC, merged

2022-05-16 10:37 UTC, caugner commented
Thank you @teoli2003 and @queengooborg! 🎉