fix(app): fix 404 page yields another 404
mdn/yari pull request #6437
Opened 2022-06-01 12:06 UTC by mustaphaturhan

## Summary

Fixes #4615

### Problem

Clicking search suggestion on 404 page yields another 404 because of `useEffect` condition. Currently, `PageOrPageNotFound` component looking for `initialPathname.current && initialPathname.current !== pathname` to be true before `setNotFound(false)` but `initialPathName` and `pathname` always the same. It isn't triggering because of that.

### Solution

- Trigger setNotFound() after client renders the page.

## How did you test this change?

On my local environment. Steps:
1. Go somewhere which throws 404 like: `http://localhost:5042/en-US/Games/Tutorials/2D_Breakout_game_pure_JavaScript`
2. Search something from search bar and click one of the results.
2.1. Old behaviour was yields you to another 404.
2.1. New behaviour is showing correct page.

2022-06-01 22:29 UTC, caugner commented on client/src/app.tsx
> +  const initialPathname = React.useRef(pathname);
Was it necessary to move this up to the `App`?

2022-06-01 22:59 UTC, caugner requested changes

2022-06-01 22:59 UTC, caugner commented on client/src/app.tsx
> +        initialPathname={initialPathname}
Could we make the decision here by introducing a `pageNotFound` state that we set to false/true in a `useEffect()` that compares initialPathname and pathname and uses `appProps.pageNotFound` only if they're equal? This should allow us to eliminate the logic inside `PageOrPageNotFound`.

2022-06-01 23:12 UTC, caugner approved these changes

2022-06-01 23:14 UTC, caugner commented on client/src/app.tsx
> +        initialPathname={initialPathname}
Went ahead and did the refactoring in 44086ba9f430ffa250e1097a6e4f5a477169d4c7 to land this.

2022-06-01 23:15 UTC, merged

2022-06-02 06:01 UTC, mustaphaturhan commented
@caugner the changes you made are looks good to me. i think it is ready to go 🎉🎉🎉

2022-06-02 10:11 UTC, caugner commented
Verified fixed on stage, thanks again! 🎉

2022-06-02 19:04 UTC, danielhjacobs commented
This seems to have mostly fixed #6161 as well, though number 5 still applies: 

> Clicking back again gives the first 404ing page, but with a different error: "Loading Error

> Error: 404 on /en-US/docs/404/index.json: Page not found"

2022-06-02 23:29 UTC, caugner commented on client/src/app.tsx
> +    }
@danielhjacobs This change might fix 5. of the referenced issue?

```suggestion
    setPageNotFound(initialPathname.current === pathname);
```

2022-06-03 00:37 UTC, caugner commented on client/src/app.tsx
> +    }
See: https://github.com/mdn/yari/pull/6459