Deprecate Compat/Specifications macro parameters
mdn/yari pull request #6576
Opened 2022-06-21 09:12 UTC by sideshowbarker

In current MDN article content, we no longer have any `Compat` or `Specifications` macros which have arguments — instead all articles use the `browser-compat` frontmatter key or the `spec-urls` frontmatter key.

And in no cases is it any longer necessary to ever call the `Compat` or `Specifications` macros with any arguments — instead in all cases, the `browser-compat` and `spec-urls` frontmatter keys can be used; therefore, it’s appropriate to report flaws for any new cases where a PR adds content that has arguments in `Compat` or `Specifications` macro calls.

2022-08-16 14:55 UTC, Elchi3 commented
Looks like test need to be updated for this (kitchensink page)

2022-08-24 11:22 UTC, caugner commented
> Looks like test need to be updated for this (kitchensink page)

Should be fixed in d111a551cd7771250844b9ca9dfed575e079af5f.

2022-08-24 11:24 UTC, caugner requested changes

2022-08-24 11:24 UTC, caugner commented on kumascript/macros/Compat.ejs
> +  deprecated; instead use the 'browser-compat' front-matter key.`);
Could we reuse `mdn.deprecated()` from `kumascript/src/api/mdn.js` by adding an optional `message` parameter?

```
  deprecated(message = "This macro has been deprecated, and should be removed.") {
    this.env.recordNonFatalError(
      "deprecated",
      message
    );
  },
```

2022-08-24 11:24 UTC, caugner commented on kumascript/macros/Specifications.ejs
> +  front-matter key.`);
ditto

2022-09-07 19:09 UTC, caugner requested changes

2022-09-07 19:09 UTC, caugner commented on kumascript/macros/Compat.ejs
> +  deprecated; instead use the 'browser-compat' front-matter key.`);
@sideshowbarker If you merge the latest `main`, you will be able to pass a message to `mdn.deprecated()`.

2022-09-08 10:09 UTC, sideshowbarker commented
@caugner Thanks much — I just now pushed an update that switches this patch to instead calling `mdn.deprecated()` with a message parameter.

2022-09-08 11:06 UTC, caugner requested changes
Compat.test.js and Specifications.test.js need to be updated to pass `browser-compat` and/or `spec-urls` via the page metadata, rather than via a parameter.

2022-09-09 11:10 UTC, sideshowbarker commented
> Compat.test.js and Specifications.test.js need to be updated to pass `browser-compat`

OK, thanks — I just now pushed an update which changes them to do that

> and/or `spec-urls` via the page metadata, rather than via a parameter

I added tests for the `spec-urls` case

2022-09-09 11:14 UTC, caugner commented
@sideshowbarker Okay, now we only need to migrate our kitchensink page, moving the bcd key into the frontmatter:

https://github.com/mdn/content/blob/5fa776ca3c79d0298cdf07c50ed0024d8b185716/files/en-us/mdn/kitchensink/index.md?plain=1#L241

2022-09-09 12:09 UTC, sideshowbarker commented
> @sideshowbarker Okay, now we only need to migrate our kitchensink page, moving the bcd key into the frontmatter:
> 
> [mdn/content@`5fa776c`/files/en-us/mdn/kitchensink/index.md?plain=1#L241](https://github.com/mdn/content/blob/5fa776ca3c79d0298cdf07c50ed0024d8b185716/files/en-us/mdn/kitchensink/index.md?plain=1#L241)

ah, ok, yes — just now opened https://github.com/mdn/content/pull/20480 for that

2022-09-09 22:23 UTC, sideshowbarker commented
With https://github.com/mdn/content/pull/20480 merged, it looks like CI here is all green now ✅

2022-09-12 16:25 UTC, caugner approved these changes

2022-09-12 16:26 UTC, merged