Suppress formal syntax expansion for <color> and <gradient>
mdn/yari pull request #6871
Opened 2022-08-12 23:06 UTC by wbamberg

This PR implements a sort of pragmatic version of one of the ideas in https://github.com/orgs/mdn/discussions/138 .

In that discussion is was suggested that when rendering formal syntax, instead of expanding out all the CSS types that we could, we should not expand out types that had their own separate MDN page, and instead just link to those pages.

A reason for wanting to do this is to make the formal syntax shorter, which is a good thing especially as pretty-printing has made it much longer than it used to be.

But as mentioned in https://github.com/orgs/mdn/discussions/138#discussioncomment-3035090, doing this for *every* type risks making formal syntax too fragmentary, forcing readers to chase across many pages to get a complete picture.

So instead this PR suppresses "inline expansion" only for the `<color>` and `<gradient>` types. The reason for choosing them is that they are very long and (especially `<color>`) very common, so the formal syntax tends to be very repetitive.

Before this PR, for example, the formal syntax for `border` looks like:

![Screen Shot 2022-08-12 at 17 03 44](https://user-images.githubusercontent.com/432915/184455111-fe8aa5e0-45e8-48ca-9446-1979d61cb941.png)

Afterwards, it looks like:

![Screen Shot 2022-08-12 at 17 02 34](https://user-images.githubusercontent.com/432915/184455058-40157fc5-7a3c-445d-9b18-57de15db0391.png)

I think the second one is quite a lot more useful for most people.

2022-08-13 04:39 UTC, teoli2003 commented
100% for not expanding `<color>` and `<gradient>`. There may be others, but that's the two main offenders.

2022-08-13 04:59 UTC, teoli2003 requested changes
A few minor changes

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
> +          (!typesToLink.includes(name))) {
```suggestion
      if (valuespaces[name]?.value && !typesToLink.includes(name)) {
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
> +        // slugMap is for when we can't derive the slug from the name
```suggestion
        // If the name is in slugMap, we can't derive the slug from the name
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
> +          // the slug does not include the angle brackets
```suggestion
          // The slug should not include the angle brackets
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
> +          // also remove the range in square brackets, as in "<number [0,∞]>"
```suggestion
          // The slug should not contain the range in square brackets, as in "<number [0,∞]>"
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
> +    // we want to ignore the constituent parts of "typesToLink" types
```suggestion
    // Ignore the constituent parts of "typesToLink" types
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
>         (!constituents.includes(node.name))) {
```suggestion
    if (node.type === 'Type' && !constituents.includes(node.name)) {
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
>      for (let constituent of allConstituents.slice(oldConstituentsLength)) {
```suggestion
    for (const constituent of allConstituents.slice(oldConstituentsLength)) {
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
>        let constituentSyntaxEntry = valuespaces[`<${constituent}>`];
```suggestion
      const constituentSyntaxEntry = valuespaces[`<${constituent}>`];
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
>        if (constituentSyntaxEntry && constituentSyntaxEntry.value) {
```suggestion
      if (constituentSyntaxEntry?.value) {
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
>  // Used for building links and tooltips for parts of the value definition syntax
```suggestion
// Descriptions used for building links and tooltips for parts of the value definition syntax
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
> +      // then link to its dedicated page
```suggestion
      // If the type is not included in the syntax, or is in "typesToLink",
      // link to its dedicated page (don't expand it)
```

2022-08-13 04:59 UTC, teoli2003 commented on kumascript/macros/CSSSyntax.ejs
>        constituents.push(node.name);
Line 319: `ast` should be `const`

2022-08-16 07:51 UTC, teoli2003 approved these changes
LGTM (be sure to check locally that it still works)

2022-08-16 12:37 UTC, fiji-flo approved these changes
Nice

2022-08-16 12:40 UTC, merged