feat(macros): localize ExperimentalBadge
mdn/yari pull request #7081
Opened 2022-09-07 02:21 UTC by yin1999

## Summary

support localization for {{ExperimentalBadge}} macro which is used by {{APIRef}}, {{experimental_inline}}, etc.

### Problem

This macro should support localization. But it won't. (the `title` and `abbreviation` is fixed with en-US text)

### Solution

use `mdn.localString` to select l10n `title` and `abbreviation` for this macro.

---

## Screenshots

In <hocalhost:5042/zh-CN/docs/Web/API/CharacterData#方法>

### Before

![image](https://user-images.githubusercontent.com/15844309/188774268-2ff042c2-c7a8-4f28-9faf-21c88fb5ed28.png)

### After

![image](https://user-images.githubusercontent.com/15844309/188774209-2f306590-10ae-40fd-a2c0-f12499cbbee9.png)

---

## How did you test this change?

run `yarn dev` and check the rendered html.

2022-09-07 02:21 UTC, yin1999 commented
Ping @irvin for a review on zh-TW translation.

2022-09-07 07:41 UTC, caugner requested changes
LGTM, but let's already add entries for the other locales.

2022-09-07 07:41 UTC, caugner commented on kumascript/macros/ExperimentalBadge.ejs
> +    "zh-TW": "實驗性。預期行為可能會在未來发生變更。"
```suggestion
    "en-US": "Experimental. Expect behavior to change in the future.",
    "es": "Experimental. Expect behavior to change in the future.",
    "fr": "Experimental. Expect behavior to change in the future.",
    "ja": "Experimental. Expect behavior to change in the future.",
    "ko": "Experimental. Expect behavior to change in the future.",
    "pt-BR": "Experimental. Expect behavior to change in the future.",
    "ru": "Experimental. Expect behavior to change in the future.",
    "zh-CN": "实验性。预期行为可能会在未来发生变更。",
    "zh-TW": "實驗性。預期行為可能會在未來发生變更。"
```

2022-09-07 07:41 UTC, caugner commented on kumascript/macros/ExperimentalBadge.ejs
> +    "zh-TW": "實驗性"
```suggestion
    "en-US": "Experimental",
    "es": "Experimental",
    "fr": "Experimental",
    "ja": "Experimental",
    "ko": "Experimental",
    "pt-BR": "Experimental",
    "ru": "Experimental",
    "zh-CN": "实验性",
    "zh-TW": "實驗性"
```

2022-09-07 07:44 UTC, caugner reviewed
@mdn/yari-content-es @mdn/yari-content-fr @mdn/yari-content-ko @mdn/yari-content-pt-br @mdn/yari-content-ru Would you like to provide translations for this macro?

- [x] es
- [x] fr
- [ ] ja
- [x] ko
- [ ] pt-BR
- [x] ru

2022-09-07 07:49 UTC, yin1999 commented
> @mdn/yari-content-es @mdn/yari-content-fr @mdn/yari-content-ko @mdn/yari-content-pt-br @mdn/yari-content-ru Would you like to provide translations for this macro?

Note for other macros which have supported localization recently:

- https://github.com/mdn/yari/blob/main/kumascript/macros/DeprecatedBadge.ejs
- https://github.com/mdn/yari/blob/main/kumascript/macros/NonStandardBadge.ejs

2022-09-07 08:00 UTC, irvin requested changes

2022-09-07 08:00 UTC, irvin commented on kumascript/macros/ExperimentalBadge.ejs
> +    "zh-TW": "實驗性。預期行為可能會在未來发生變更。"
```suggestion
    "zh-TW": "實驗性。行為可能會在未來發生變動。"
```

2022-09-07 08:03 UTC, irvin requested changes
to be more clear

2022-09-07 08:03 UTC, irvin commented on kumascript/macros/ExperimentalBadge.ejs
> +    "zh-TW": "實驗性"
```suggestion
    "zh-TW": "實驗性質"
```

2022-09-07 11:59 UTC, SphinxKnight requested changes
Suggestion for `fr`
Thanks @yin1999 🙏 / @caugner 
Let me know if you prefer to proceed differently.

2022-09-07 11:59 UTC, SphinxKnight commented on kumascript/macros/ExperimentalBadge.ejs
> +    "fr": "Experimental",
```suggestion
    "fr": "Expérimental",
```

2022-09-07 11:59 UTC, SphinxKnight commented on kumascript/macros/ExperimentalBadge.ejs
> +    "fr": "Experimental. Expect behavior to change in the future.",
```suggestion
    "fr": "Expérimental. Le comportement attendu pourrait évoluer à l'avenir.",
```

2022-09-07 16:11 UTC, marcelozarate requested changes
_Experimental_ word matches spanish usage and meaning. Hope it helps!

2022-09-07 16:11 UTC, marcelozarate commented on kumascript/macros/ExperimentalBadge.ejs
> +    "es": "Experimental. Expect behavior to change in the future.",
```suggestion
    "es": "Experimental. Espere que el comportamiento cambie en el futuro.",
```

2022-09-07 18:26 UTC, caugner commented
> Would you like to provide translations for this macro?

Forgot to ping @mdn/yari-content-ja

2022-09-12 18:27 UTC, hochan222 requested changes
Suggestion for ko, Thanks!

@mdn/yari-content-ko, Let me know if you prefer to proceed differently.

2022-09-12 18:27 UTC, hochan222 commented on kumascript/macros/ExperimentalBadge.ejs
> +    "ko": "Experimental. Expect behavior to change in the future.",
```suggestion
    "ko": "Experimental. 예상되는 동작은 향후 변경될 수 있습니다.",
```

2022-09-12 19:03 UTC, caugner commented
Thanks to everyone who already provided their translations. 🙏 

⏳ I'll wait another 36h hours before merging, in case @mdn/yari-content-ja or @mdn/yari-content-pt-br would like to provide theirs.

2022-09-14 07:51 UTC, caugner approved these changes

2022-09-14 07:52 UTC, merged