chore(scripts): add macro-usage-report
mdn/yari pull request #7087
Opened 2022-09-07 16:43 UTC by caugner

## Summary

Adds a script that counts how often each script is used in content/translated-content.

### Problem

We have a lot of macros, and we don't have an overview of how often each macro is used.

### Solution

Implement a script that searches for all macro occurrences using `rg` (ripgrep).

---

<details><summary>

## Result
</summary>

| macro | content | translated_content |
|:----- |:------- |:------------------ |
| AddonSidebar | <details><summary>672</summary><ul><li>/en-us/mozilla/add-ons/contact_us/index.md</li><li>/en-us/mozilla/add-ons/index.md</li><li>... (667 more)</li></ul></details> | <details><summary>1094</summary><ul><li>/es/mozilla/add-ons/index.html</li><li>/es/mozilla/add-ons/webextensions/add_a_button_to_the_toolbar/index.html</li><li>... (1089 more)</li></ul></details> |
| AddonSidebarMain | :o: | :o: |
| APIListAlpha | <details><summary>1</summary><ul><li>/en-us/web/api/index.md</li></ul></details> | <details><summary>8</summary><ul><li>/es/web/api/index.html</li><li>/fr/web/api/index.md</li><li>... (3 more)</li></ul></details> |
| APIRef | <details><summary>5125</summary><ul><li>/en-us/mdn/kitchensink/index.md</li><li>/en-us/mdn/writing_guidelines/howto/json_structured_data/index.md</li><li>... (5120 more)</li></ul></details> | <details><summary>6937</summary><ul><li>/es/conflicting/web/api/blob/index.html</li><li>/es/conflicting/web/api/canvasrenderingcontext2d/index.md</li><li>... (6932 more)</li></ul></details> |
| ARIARole | <details><summary>40</summary><ul><li>/en-us/mdn/kitchensink/index.md</li><li>/en-us/mdn/writing_guidelines/page_structures/page_types/html_element_page_template/index.md</li><li>... (35 more)</li></ul></details> | <details><summary>128</summary><ul><li>/es/web/html/element/a/index.html</li><li>/es/web/html/element/dl/index.html</li><li>... (123 more)</li></ul></details> |
| AvailableInWorkers | <details><summary>257</summary><ul><li>/en-us/mdn/kitchensink/index.md</li><li>/en-us/mdn/writing_guidelines/page_structures/macros/commonly_used_macros/index.md</li><li>... (252 more)</li></ul></details> | <details><summary>609</summary><ul><li>/es/mdn/writing_guidelines/page_structures/macros/commonly_used_macros/index.md</li><li>/es/orphaned/web/api/navigatorconcurrenthardware/hardwareconcurrency/index.md</li><li>... (604 more)</li></ul></details> |
| bug | <details><summary>156</summary><ul><li>/en-us/glossary/quality_values/index.md</li><li>/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.md</li><li>... (151 more)</li></ul></details> | <details><summary>522</summary><ul><li>/es/mozilla/firefox/experimental_features/index.html</li><li>/es/mozilla/firefox/releases/30/index.md</li><li>... (517 more)</li></ul></details> |
| CanvasSidebar | <details><summary>16</summary><ul><li>/en-us/web/api/canvas_api/index.md</li><li>/en-us/web/api/canvas_api/manipulating_video_using_canvas/index.md</li><li>... (11 more)</li></ul></details> | <details><summary>112</summary><ul><li>/es/orphaned/web/api/canvas_api/a_basic_ray-caster/index.html</li><li>/es/web/api/canvas_api/index.html</li><li>... (107 more)</li></ul></details> |
| Compat | <details><summary>8548</summary><ul><li>/en-us/mdn/kitchensink/index.md</li><li>/en-us/mdn/writing_guidelines/howto/document_an_http_header/index.md</li><li>... (8543 more)</li></ul></details> | <details><summary>18086</summary><ul><li>/es/conflicting/web/api/blob/index.html</li><li>/es/conflicting/web/api/element/click_event/index.html</li><li>... (18081 more)</li></ul></details> |
| CompatAndroid | :o: | :o: |
| CompatChrome | :o: | :o: |
| CompatGeckoDesktop | :o: | :o: |
| CompatGeckoMobile | :o: | :o: |
| CompatibilityTable | :o: | :o: |
| CompatNo | :o: | :o: |
| CompatUnknown | :o: | :o: |
| CompatVersionUnknown | :o: | :o: |
| CSP | <details><summary>40</summary><ul><li>/en-us/glossary/document_directive/index.md</li><li>/en-us/glossary/fetch_directive/index.md</li><li>... (35 more)</li></ul></details> | <details><summary>85</summary><ul><li>/es/web/http/csp/index.html</li><li>/es/web/http/headers/content-security-policy/index.html</li><li>... (80 more)</li></ul></details> |
| CSS_key_concepts | :o: | <details><summary>38</summary><ul><li>/es/web/css/actual_value/index.html</li><li>/es/web/css/at-rule/index.html</li><li>... (33 more)</li></ul></details> |
| CSS_Ref | <details><summary>1</summary><ul><li>/en-us/web/css/reference/index.md</li></ul></details> | <details><summary>8</summary><ul><li>/es/web/css/reference/index.html</li><li>/fr/web/css/reference/index.md</li><li>... (3 more)</li></ul></details> |
| CSSAnimatedProperties | <details><summary>1</summary><ul><li>/en-us/web/css/css_animated_properties/index.md</li></ul></details> | <details><summary>4</summary><ul><li>/fr/web/css/css_animated_properties/index.md</li><li>/ja/web/css/css_animated_properties/index.md</li><li>... (-1 more)</li></ul></details> |
| CSSInfo | <details><summary>162</summary><ul><li>/en-us/mdn/writing_guidelines/page_structures/page_types/css_property_page_template/index.md</li><li>/en-us/web/css/--_star_/index.md</li><li>... (157 more)</li></ul></details> | <details><summary>249</summary><ul><li>/es/web/css/--_star_/index.html</li><li>/es/web/css/-moz-float-edge/index.md</li><li>... (244 more)</li></ul></details> |
| CSSRef | <details><summary>955</summary><ul><li>/en-us/mdn/writing_guidelines/page_structures/page_types/css_property_page_template/index.md</li><li>/en-us/mdn/writing_guidelines/page_structures/page_types/css_selector_page_template/index.md</li><li>... (950 more)</li></ul></details> | <details><summary>3547</summary><ul><li>/es/orphaned/web/css/-moz-context-properties/index.html</li><li>/es/orphaned/web/css/css_animations/detecting_css_animation_support/index.html</li><li>... (3542 more)</li></ul></details> |
| CSSSyntax | <details><summary>41</summary><ul><li>/en-us/mdn/kitchensink/index.md</li><li>/en-us/mdn/writing_guidelines/page_structures/page_types/css_property_page_template/index.md</li><li>... (36 more)</li></ul></details> | <details><summary>187</summary><ul><li>/es/web/css/--_star_/index.html</li><li>/es/web/css/_colon_blank/index.html</li><li>... (182 more)</li></ul></details> |
| CSSTutorialTOC | :o: | :o: |
| cssxref | <details><summary>1248</summary><ul><li>/en-us/games/techniques/crisp_pixel_art_look/index.md</li><li>/en-us/glossary/accent/index.md</li><li>... (1243 more)</li></ul></details> | <details><summary>3776</summary><ul><li>/es/glossary/block/css/index.md</li><li>/es/glossary/flex/index.md</li><li>... (3771 more)</li></ul></details> |
| DefaultAPISidebar | <details><summary>432</summary><ul><li>/en-us/web/api/audioscheduledsourcenode/ended_event/index.md</li><li>/en-us/web/api/authenticatorassertionresponse/authenticatordata/index.md</li><li>... (427 more)</li></ul></details> | <details><summary>515</summary><ul><li>/es/web/api/battery_status_api/index.md</li><li>/es/web/api/clipboard_api/index.html</li><li>... (510 more)</li></ul></details> |
| Deprecated_Header | <details><summary>390</summary><ul><li>/en-us/mdn/kitchensink/index.md</li><li>/en-us/mdn/writing_guidelines/page_structures/page_types/api_constructor_subpage_template/index.md</li><li>... (385 more)</li></ul></details> | <details><summary>95</summary><ul><li>/es/web/api/window/applicationcache/index.md</li><li>/fr/mozilla/add-ons/webextensions/api/extension/sendrequest/index.md</li><li>... (90 more)</li></ul></details> |
| Deprecated_Inline | <details><summary>151</summary><ul><li>/en-us/glossary/document_directive/index.md</li><li>/en-us/glossary/fetch_directive/index.md</li><li>... (146 more)</li></ul></details> | <details><summary>179</summary><ul><li>/es/mdn/writing_guidelines/page_structures/macros/commonly_used_macros/index.md</li><li>/es/web/api/document/index.md</li><li>... (174 more)</li></ul></details> |
| DeprecatedBadge | :o: | :o: |
| DeprecatedGeneric | :o: | :o: |
| DiscussionList | :o: | <details><summary>16</summary><ul><li>/es/web/accessibility/community/i [...]

2022-09-07 17:26 UTC, caugner commented
@yin1999 @teoli2003 @SphinxKnight This might be interesting for you.

2022-09-07 18:21 UTC, caugner commented
@yin1999 Would you like to open two PRs for removing `CompatAndroid` and `CSSTutorialTOC`?

React to this comment with 👀 when you (or anybody else) starts working on it.

2022-09-08 08:22 UTC, teoli2003 commented
Strangely, I found a call to `xref_cssvisual` in https://github.com/mdn/content/blob/main/files/en-us/web/css/-webkit-mask-box-image/index.md while the script returns none.

2022-09-08 08:48 UTC, caugner commented
> Strangely, I found a call to `xref_cssvisual` in https://github.com/mdn/content/blob/main/files/en-us/web/css/-webkit-mask-box-image/index.md while the script returns none.

Good catch, it looks like the parentheses in `Xref_cssvisual()` are considered part of the word, so it doesn't match `xref_cssvisual\b`.

2022-09-08 09:51 UTC, caugner commented
> Strangely, I found a call to `xref_cssvisual` in https://github.com/mdn/content/blob/main/files/en-us/web/css/-webkit-mask-box-image/index.md while the script returns none.

@teoli2003 I have now fixed that bug, thanks for reporting. 👍

2022-10-09 08:33 UTC, yin1999 commented
Maybe we should ignore `_redirects.txt`, for there is a redirect like this (maybe a mistake):

https://github.com/mdn/translated-content/blob/8ed6dea31e84cf67e2f413a6f47ba751350abc13/files/fr/_redirects.txt#L1847

```
/fr/docs/HTML/Element/Output_{{HTMLVersionInline(5)}}_{{fx_minversion_inline(4)}}	/fr/docs/Web/HTML/Element/Output
```

2022-10-09 10:26 UTC, SphinxKnight commented
> Maybe we should ignore `_redirects.txt`, for there is a redirect like this (maybe a mistake):
> 
> https://github.com/mdn/translated-content/blob/8ed6dea31e84cf67e2f413a6f47ba751350abc13/files/fr/_redirects.txt#L1847
> 
> ```
> /fr/docs/HTML/Element/Output_{{HTMLVersionInline(5)}}_{{fx_minversion_inline(4)}}	/fr/docs/Web/HTML/Element/Output
> ```
> 
> Or we can remove this redirect? /cc @SphinxKnight 

let me get to it, this one scratches like an itch :)

2022-10-19 12:50 UTC, SphinxKnight commented
Redirects removed w/ https://github.com/mdn/translated-content/pull/9343

2022-12-06 13:38 UTC, caugner commented on package.json
> +    "macro-usage-report": "ts-node scripts/macro-usage-report.ts",
```suggestion
```

2022-12-06 13:38 UTC, caugner commented on tool/macro-usage-report.ts
> +function formatCell(files: string[], limit = 2): string {
```suggestion
function formatCell(files: string[]): string {
```

2022-12-07 18:18 UTC, fiji-flo requested changes
Fails if `CONTENT_TRANSLATED_ROOT` is not set.

2022-12-08 10:33 UTC, caugner commented
> Fails if `CONTENT_TRANSLATED_ROOT` is not set.

Fixed in bf171dfd9.

2022-12-08 17:44 UTC, nschonni commented
Had a side thought about this. What about instead of adding this to the CLI itself, just adding CI cron job + manual trigger to the repo for this, and have it create/update an issue?

2022-12-08 18:46 UTC, caugner commented
> Had a side thought about this. What about instead of adding this to the CLI itself, just adding CI cron job + manual trigger to the repo for this, and have it create/update an issue?

Adding a workflow for this is an idea worth pursuing, but rather out of the scope of this PR. You would probably still need the CLI command itself, but given that it can produce JSON with `--format=json`, it might even be possible to automatically open or update a PR removing all unused macros. Also, I wouldn't be sure that `rg` is available on GitHub runners (maybe it is).

2022-12-08 18:56 UTC, nschonni commented
Different approach, since it's used to comment on each PR, but something you can copy a little for the commenting with action/github-script if you decide to try that later https://github.com/w3c/aria-practices/blob/main/.github/workflows/coverage-report.yml

2022-12-08 21:08 UTC, caugner commented
@nschonni Can you elaborate your proposal? I thought you were suggesting to automatically open an issue if a macro is no longer used. :)

2022-12-16 09:34 UTC, caugner reviewed
Self-approval, as @fiji-flo's only concern was that it failed if `CONTENT_TRANSLATED_ROOT` was not set, which is now fixed.

2022-12-16 09:37 UTC, merged