Add translated-content to recent contributions tile on homepage
mdn/yari pull request #7250
Opened 2022-09-28 04:18 UTC by SphinxKnight

## Summary

I have discovered the "Recent contributions" tile on the homepage from the redesign and I like how it exposes the open source nature of MDN.

### Problem

However, there were no reference of https://github.com/mdn/translated-content/ :(

### Solution

Hack the thing so that contributions from mdn/translated-content are visible as well

## Screenshots

### Before

![image](https://user-images.githubusercontent.com/2413436/192686497-68c155a9-0da3-4dda-9457-2c899f218b6e.png)

### After

![image](https://user-images.githubusercontent.com/2413436/192686437-9656e291-7ada-469c-8da3-0333f29bf89a.png)

## How did you test this change?

Ran it locally.

cc @mdn/localization-team-leads / @mdn/mdn-community-engagement

2022-09-28 12:42 UTC, schalkneethling commented
Thank you for this @SphinxKnight, I for one support this idea.

2022-10-19 18:25 UTC, caugner commented
We will have to defer this to the product team, because they "own" the homepage.

Maybe we could show different "Recent contributions" depending on the locale:

- https://developer.mozilla.org/en-US would show only content PRs.
- https://developer.mozilla.org/fr would show additonally/instead French translated-content PRs (tagged with `l10n-fr` label).

2022-10-20 13:34 UTC, SphinxKnight commented
> Maybe we could show different "Recent contributions" depending on the locale:

Why should contributions be divided depending on the locale?

2022-10-20 18:00 UTC, caugner commented
We have discussed this internally and have aligned on showing the last 5 contributions from mdn/content and the last 5 contributions from mdn/translated-content together. 🎉 

We don't have capacity to implement this ourselves in the next 14 days, but we're happy to merge a community PR earlier! 🙏

2022-10-20 18:27 UTC, caugner requested changes
The sort doesn't work, otherwise LGTM 👍, just one nit and another suggestion.

2022-10-20 18:27 UTC, caugner commented on build/spas.ts
> +    .sort((a, b) => a.updated_at - b.updated_at);
`updated_at` are strings, so they cannot be subtracted:

```suggestion
    .sort((a, b) => a.updated_at < b.updated_at ? 1 : -1);
```

2022-10-20 18:27 UTC, caugner commented on build/spas.ts
> +async function fetchGitHubPRs(repo = "mdn/content", count = 5) {
We don't really need a default value for repo here:

```suggestion
async function fetchGitHubPRs(repo, count = 5) {
```

2022-10-20 18:27 UTC, caugner commented on build/spas.ts
> +    .sort((a, b) => a.updated_at - b.updated_at);
Maybe we can make this more elegant:

```suggestion
  const repos = ["mdn/content", "mdn/translated-content"];
  const countPerRepo = 5;
  const pullRequests = (
    await Promise.all(
      repos.map(async (repo) => await fetchGitHubPRs(repo, countPerRepo))
    )
  ).flat();
  const pullRequestsData = pullRequests.sort((a, b) =>
    a.updated_at < b.updated_at ? 1 : -1
  );
```

2022-10-24 09:44 UTC, SphinxKnight commented
Thanks a lot for the review @caugner, I'll take care of fixing those today or tomorrow.

2022-10-24 09:44 UTC, SphinxKnight commented on build/spas.ts
> +    .sort((a, b) => a.updated_at - b.updated_at);
far more elegant indeed 🙇‍♂️

2022-10-25 18:56 UTC, caugner approved these changes

2022-10-25 18:57 UTC, merged

2022-10-25 18:57 UTC, caugner commented
Thank you @SphinxKnight! 🎉