fix(plus): add breadcrumbs for Collections/Notifications/Settings
mdn/yari pull request #7267
Opened 2022-09-30 04:02 UTC by caugner

## Summary

Adds breadcrumbs for Collections/Notifications/Settings in MDN Plus.

### Problem

MDN Plus did not have breadcrumbs (except for the "Documentation" section).

### Solution

Make it easy to add breadcrumbs to non-Doc pages.

---

## Screenshots

### Before

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/495429/193187593-8290e4fc-a155-4b0b-b367-3a44cfd19e11.png">

### After

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/495429/193187549-082c6c02-22e9-42b5-bf00-c7ffffc69d36.png">

---

## How did you test this change?

Checked out these pages locally:

- http://localhost:3000/en-US/plus/collections
- http://localhost:3000/en-US/plus/notifications
- http://localhost:3000/en-US/plus/settings

2022-10-18 13:19 UTC, Guyzeroth requested changes

2022-10-18 13:19 UTC, Guyzeroth commented on client/src/plus/index.tsx
> +  const userData = useUserData();
Not used.

2022-10-18 13:20 UTC, Guyzeroth commented
1 change then LGTM. Thanks for picking that up 👍

2022-10-18 15:31 UTC, caugner commented on client/src/plus/index.tsx
> +  const userData = useUserData();
```suggestion
```

2022-10-18 15:32 UTC, caugner commented on client/src/plus/index.tsx
> +import { useUserData } from "../user-context";
```suggestion
```

2022-10-19 14:47 UTC, Guyzeroth commented
Coolio. Thanks! :)

2022-10-19 14:47 UTC, merged