enchance(build): write metadata.json with hashes and browser compat
mdn/yari pull request #7487
Opened 2022-11-04 10:27 UTC by fiji-flo

## Summary

Adds a `metadata.json` per locale. This contains the sha256sum of all `index.json`s, too. This will be used to sync metadata with rumba in the future.

2022-11-04 17:45 UTC, LeoMcA requested changes
Needs some small changes, especially renaming one of the `metadata` objects.

Do we need to be concerned about the size of these json blobs? is something in the tens of MB for each locale going to massively slow down the upload stage of the build?

2022-11-04 17:45 UTC, LeoMcA commented on build/index.ts
> +      : [browserCompat];
This is ending up as `[null]` for docs without a bcd table.

Struggling to come up with something better than 
```suggestion
  doc.browserCompat = browserCompat
    ? Array.isArray(browserCompat)
      ? browserCompat
      : [browserCompat]
    : undefined;
```

2022-11-08 11:28 UTC, LeoMcA approved these changes
lgtm!

2022-11-10 09:42 UTC, Guyzeroth approved these changes

2022-11-10 12:57 UTC, merged