Replace outdated footer links with GitHub links
mdn/yari pull request #7538
Opened 2022-11-10 07:08 UTC by ljcool2006

Recently the site has removed the old sections of these links without any replacement (as far as I'm aware); temporarily replacing them with direct github links for now until we get a reliable replacement

## Summary

### Problem

### Solution

---

## Screenshots

### Before

### After

---

## How did you test this change?

2022-11-10 09:43 UTC, caugner requested changes
Hi @ljcool2006, welcome to yari and thank you for your contribution, good catch! 👋 

We shortly discussed this internally, and would like to merge both links into a single "Report an issue" link that points to https://developer.mozilla.org/en-US/docs/MDN/Community/Issues (with `en-US` being replaced by the locale). Could you update your PR accordingly? Thanks a lot. 🙏

2022-11-10 19:53 UTC, ljcool2006 reviewed
Done

2022-11-11 08:54 UTC, caugner approved these changes

2022-11-11 09:01 UTC, merged

2022-11-11 09:01 UTC, caugner commented
Thank you @ljcool2006! 🙏