chore(community): update links + wordings
mdn/yari pull request #7558
Opened 2022-11-12 02:15 UTC by MrBrain295

## Summary
Fix some links and grammar. Fix: #6619

### Problem
Some stuff is outdated.

### Solution
Update it.

---

## Screenshots

### Before

### After

---

## How did you test this change?

2022-11-14 13:32 UTC, caugner requested changes
LGTM. Can you please also replace the other two occurences of `Web` by `web` on the page?

2022-11-14 21:42 UTC, MrBrain295 commented
@caugner I can’t seem to find the remaining occurrences.

2022-11-15 14:10 UTC, caugner approved these changes

2022-11-15 14:10 UTC, merged

2022-11-15 14:10 UTC, caugner commented
Thanks @MrBrain295! 🙏