fix(build): match bad_src flaws for markdown files
mdn/yari pull request #8133
Opened 2023-02-05 02:07 UTC by yin1999

## Summary

As we are 100% markdown now, but the images check will only match src in HTML files (see function `findMatchesInText`).

And we already have a function `findMatchesInMarkdown`, which is used to match links in markdown.  I just reuse this function to match image's src. So we could show bad src flaws for markdown files.

### Problem

The bad_src flaws for image files are only works for html files. So we couldn't be notified when there is a bad image src within a markdown document.

### Solution

chech whether the document is a markdown file. If so, use `findMatchesInMarkdown` to match image's src.

To make this be a test, convert the bad_image test file to markdown (as we are 100% markdown now).

---

## Screenshots

Try to add a image (with bad image src) in document: `files/zh-cn/mdn/at_ten/index.md`

![image](https://user-images.githubusercontent.com/15844309/216797801-85bbd120-64f9-4a63-9a39-f483d86e9cac.png)

Then, run `yarn dev` and open `http://localhost:5042/zh-CN/docs/MDN/At_ten/index.json`

### Before

We could not see the bad_src flaws

![image](https://user-images.githubusercontent.com/15844309/216797829-1985e8d8-570b-4e58-ad5b-a3b989361455.png)

### After

We could see the bad_src flaws

![image](https://user-images.githubusercontent.com/15844309/216797816-b436924e-9c3a-4122-b1af-c946f7463ff9.png)

---

## How did you test this change?

run `yarn dev` and `yarn test`

2023-02-05 02:11 UTC, yin1999 commented on build/matches-in-text.ts
> +export function findMatchesInText(
let this be a normal function, for we have convert all the results to an array in usage

2023-02-06 06:57 UTC, yin1999 commented on build/check-images.ts
> +        });
As we still have many HTML tables in content. Is it necessary to match both in Markdown and Text for markdown files?

example: mdn/content#24154

2023-02-06 18:00 UTC, caugner requested changes
LGTM, just some nits.

2023-02-06 18:00 UTC, caugner commented on testing/content/files/en-us/web/images/bad_src/index.md
> +![](empty.gif)
Let's keep one of the HTML images (if necessary, wrapping it in a table), to be able to test that we check Markdown and HTML images.

2023-02-07 01:16 UTC, yin1999 commented on build/check-images.ts
> +        });
Hi @caugner, as we need to sort the matches, so the codes might be:

```ts
const matches = findMatchesInText(src, rawContent, {
  attribute: "src",
});
if (isMarkdown) {
  const hasMatchInHTML = matches.length > 0;
  matches.push(
    ...findMatchesInMarkdown(src, rawContent, { type: "image" })
  );
  // note that, we need to sort them by line and column
  if (hasMatchInHTML) {
    matches.sort((a, b) =>
      a.line === b.line ? a.column - b.column : a.line - b.line
    );
  }
}
```

I'm not sure could we call `findMatchesInText` function in `findMatchesInMarkdown` as we could deal with broken html format links in markdown file.

2023-02-08 02:22 UTC, yin1999 commented on build/check-images.ts
> +        });
Found that the [`fromMarkdown`](https://github.com/syntax-tree/mdast-util-from-markdown#syntax-tree) can also parse html nodes: see [AST](https://github.com/syntax-tree/mdast).

Resolved this by also parse HTML node in markdown

2023-02-08 02:29 UTC, yin1999 commented on build/check-images.ts
> +    const match = matches[checkedBefore];
As we use `i !== checkedBefore` as a filter to get the correct match, use length check and get item by index instead

2023-02-08 02:29 UTC, yin1999 commented on testing/tests/index.test.ts
> +  // Check the line and column numbers for html <img> tags in markdown
It seems that the start column of markdown images are the index of `!` (+1). Only add line and column test for html <img> elements

2023-02-08 04:50 UTC, yin1999 commented
Trying to fix the testing error in mdn/content#24265

2024-02-29 16:48 UTC, caugner approved these changes
LGTM.

@yin1999 Can you double-check that it still works as expected?

2024-03-01 08:49 UTC, yin1999 commented
> LGTM.
> 
> @yin1999 Can you double-check that it still works as expected?

Hey @caugner. This still works, I've only found the fix flow functionality does not work for HTML code in markdown file, as the `replaceMatchingLinksInMarkdown` only replace markdown links. There is still a lot of work to be done in the future to fix the functionality of flaws fixing :)

Addition: I've add dev dependency `"mdast-util-directive"` to support type inference in 74621d28c2edacb6d4641e290362c0f75dd85f32.

2024-03-01 16:56 UTC, caugner approved these changes
LGTM, just tested it locally once more. Great work! 🎉

2024-03-01 16:56 UTC, merged