Create a PWA sidebar
mdn/yari pull request #8238
Opened 2023-02-17 04:09 UTC by wbamberg

@captainbrosset, @estelle, this is a draft PR for a PWA sidebar, just to give a feel for what it might look like.

To see something you need to:
- check out this branch
- check out https://github.com/wbamberg/content/tree/pwa
- point the .env from this Yari at your checkout of https://github.com/wbamberg/content/tree/pwa
- run `yarn dev`
- go to http://localhost:3000/en-US/docs/Web/Progressive_web_apps.

2023-02-20 08:26 UTC, captainbrosset commented
Thanks a lot @wbamberg. Sadly I have no had the time to go through this. 
By any chance, could you attach a screenshot of the sidebar here? I know that would help me a lot!

2023-02-20 19:34 UTC, wbamberg commented
Sorry Patrick, I forget some people don't live inside this world :).

Not expanded:

<img width="304" alt="Screen Shot 2023-02-20 at 11 21 12 AM" src="https://user-images.githubusercontent.com/432915/220184939-2491c041-2ffb-4a55-8453-1359bf853cca.png">

Expanded:

<img width="330" alt="Screen Shot 2023-02-20 at 11 21 37 AM" src="https://user-images.githubusercontent.com/432915/220184966-348ee6b7-186f-4f04-8bd0-8e23366fc875.png">

The names for tutorials and tutorial steps are placeholders.

One thing worth mentioning is that when an item in the sidebar has a disclosure arrow, like "Your first PWA", (meaning it contains a group of connected subpages, like steps in a tutorial) it can't also be a link to a page (because clicking the label opens the subpages), so if we want an overview page for this we usually end up having that be the first child, like:

```
* Your first PWA
    * Your first PWA
    * Step 1
    * Step 2
    ...
```

...this is ugly and I wish we had a better answer here, but it's what we do everywhere.

2023-02-21 09:17 UTC, captainbrosset commented
This looks great.

A couple of thoughts:

* Do we need to be concerned about the length of the sidebar? The **How-to** section is likely to contain 15 to 20 topics which, for now, would just be presented in one flat list.

* What do you think should go under **Reference**? We discussed about creating a global PWA reference page which would contain links to all manifest, https, service worker, etc. things. Do you think we should also add a link to manifest, and service worker reference docs in the sidebar directly?

* I'm not too worried about the fact that TOC nodes can't also be links. We have the same issue on learn.microsoft.com and I don't find this to be a big issue myself. At least, as a user, I'm not confused about whether I should read some intro content on the TOC node first, or expand it to find the first page inside of it. I see what you mean about having to repeat the title. But I'm sure we can find creative ways to avoid this:
   
   * Tutorials
     * Build a simple PWA
        * Get started
        * Add a manifest
        * Install the PWA
      * Build a more complex PWA

   The 2 tutorial names would have to be better than this, but the idea is to find a title for them.

2023-02-21 17:56 UTC, estelle commented
this LGTM. I like the idea of nesting subcontent.

I assume, like on https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started, the current section would be open and hilited, and everything else will be closed, which I think will make this nav great UX as long as we don't have every other subject listed in the nav, like the learn section does :|

2023-02-21 17:58 UTC, wbamberg commented
> I assume, like on https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started, the current section would be open and hilited, and everything else will be closed, which I think will make this nav great UX as long as we don't have every other subject listed in the nav, like the learn section does :|

Yes - and if you try this sidebar out your should see that behavior.

2023-02-21 18:04 UTC, wbamberg commented
> This looks great.
> 
> A couple of thoughts:
> 
>     * Do we need to be concerned about the length of the sidebar? The **How-to** section is likely to contain 15 to 20 topics which, for now, would just be presented in one flat list.

I think 15-20 is fine in a flat list, but if it looks too big we could create additional categories.

>     * What do you think should go under **Reference**? We discussed about creating a global PWA reference page which would contain links to all manifest, https, service worker, etc. things. Do you think we should also add a link to manifest, and service worker reference docs in the sidebar directly?

I'd envisaged this is just one page with nothing under it, linking to the reference docs that live elsewhere. We could have links to say https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API direct from the sidebar, and maybe that would be good. We get a bit into sidebar philosophy though :) of whether sidebars should contain links to pages that themselves have a different sidebar. We do this sometimes on MDN, and it works fine now but rules out certain possible futures for sidebars (see https://github.com/orgs/mdn/discussions/124#discussioncomment-4578532 for example: it makes it much harder to use lists of links in sidebars be reusable bits of content). But like I say, we do this already sometimes, so it is certainly possible.

2023-02-24 10:03 UTC, caugner requested changes

2023-02-24 10:03 UTC, caugner commented on kumascript/macros/PWASidebar.ejs
> +    )}</a></li>`;
Probably makes sense to extract `renderLink()`, which determines both the `href` and the text.

If the page does not exist in the current locale, I think we'll want to add `(en-US)` behind, like `web.smartlink()` already does (I don't mind not using `web.smartlink()` for now, but we should extract all these helper methods somewhere before replicating them to another sidebar anyways).

2023-02-24 10:03 UTC, caugner commented on kumascript/macros/PWASidebar.ejs
> +  let output = '<section id="Quick_links"><ol>';
This one is a brand-new requirement to [measure sidebar_clicks per macro](https://github.com/mdn/yari/pull/8293):

```suggestion
  let output = '<section id="Quick_links" data-macro="PWASidebar"><ol>';
```

2023-04-04 04:12 UTC, wbamberg commented
I've updated this sidebar with the new pages we've written, and to include the existing pages until we are ready to replace them all. I've also addressed review comments.

Overall structure here is pretty much the same as what we had before.

Details of the content changes are in https://github.com/mdn/content/pull/25888. This PR needs to land with that one.

2023-04-04 09:40 UTC, caugner requested changes
LGTM, just two refactoring opportunities (+ one older comment regarding the `(en-US)` postfix).

2023-04-04 09:40 UTC, caugner commented on kumascript/macros/PWASidebar.ejs
> +  )}</strong></a></li>`;
Let's extract this as `renderRootItem()` to describe what this does?

2023-04-04 09:40 UTC, caugner commented on kumascript/macros/PWASidebar.ejs
> +  }
Let's do the same as in line 59:

```suggestion
  output += (await Promise.all(sections.map(section => renderSection(section)))).join('');
```

2023-04-04 16:58 UTC, wbamberg commented
> LGTM, just two refactoring opportunities (+ one older comment regarding the `(en-US)` postfix).

Sorry, I forgot about the paths thing (I remembered much too late to add to this PR!). Much better this way.

2023-04-04 19:12 UTC, caugner approved these changes
LGTM, just one trailing slash that can probably be removed.

2023-04-04 19:12 UTC, caugner commented on kumascript/macros/PWASidebar.ejs
> +  sidebarURL: "/docs/Web/Progressive_web_apps/",
Trailing slash:

```suggestion
  sidebarURL: "/docs/Web/Progressive_web_apps",
```

2023-04-04 19:13 UTC, caugner commented
@wbamberg Now that this PR is no longer a draft, would you mind updating the PR description to follow [our template](https://github.com/mdn/yari/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1)? 🙌

2023-04-05 07:31 UTC, captainbrosset approved these changes

2023-04-05 14:32 UTC, merged

2023-04-05 16:25 UTC, caugner commented
Awesome work, @captainbrosset and @wbamberg! 🎉