fix(macros/Deprecated_Header): add note msg when version is not provided
mdn/yari pull request #8339
Opened 2023-03-05 02:02 UTC by yin1999

## Summary

The `Deprecated` note may be removed by mistake, just add it back when the version is not provided.

### Problem

See:

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menuitem

![image](https://user-images.githubusercontent.com/15844309/222937412-079fd53b-717c-4443-8de9-db842a521a44.png)

### Solution

When the version is not provided, use `Deprecated` note instead (copying from:

https://github.com/mdn/yari/blob/cd6c1176827a3afc8f53460c66280cd26db5804a/kumascript/macros/Deprecated_Inline.ejs#L18-L27

---

## Screenshots

See those pages:

- with version param: `http://localhost:5042/fr/docs/Web/HTML/Element/menuitem`

    ![image](https://user-images.githubusercontent.com/15844309/222937591-e38b9e46-b779-4623-ad66-6fa1fea89c6c.png)

- with version param (digits): `http://localhost:5042/es/docs/Web/API/IDBCursor#constants`

    ![image](https://user-images.githubusercontent.com/15844309/222937571-a7a28399-9112-4995-92f5-b6042c46aba9.png)

- with version param (empty string): `http://localhost:5042/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/getYear`

    ![image](https://user-images.githubusercontent.com/15844309/222937554-dc38dc28-306c-4367-8ea1-8ee119384157.png)

- without version param: `http://localhost:5042/en-US/docs/Web/HTML/Element/menuitem`

    ![image](https://user-images.githubusercontent.com/15844309/222937614-6d863e26-0399-4e99-9610-325178999289.png)

---

## How did you test this change?

run `yarn dev` and see the rendered pages.

2023-03-05 02:03 UTC, yin1999 commented on kumascript/macros/Deprecated_Header.ejs
> +  version = `gecko ${version}`;
adding a space between `gecko` and the version. I think it's better

2023-03-06 14:16 UTC, caugner requested changes
Good catch, thank you!

Just one nit.

2023-03-06 14:16 UTC, caugner commented on kumascript/macros/Deprecated_Header.ejs
> +const noteMsg = version || note;
Let's inline this variable in line 36.

```suggestion
```

2023-03-06 14:29 UTC, yin1999 commented on kumascript/macros/Deprecated_Header.ejs
> +    <h4><%-noteMsg%></h4>
Just made a local test and it works.

2023-03-06 14:54 UTC, merged