docs(README): sync require nodejs version
mdn/yari pull request #8340
Opened 2023-03-05 02:21 UTC by daiwanxing

## Summary

### Problem

### Solution

---

## Screenshots

### Before

### After

---

## How did you test this change?

2023-03-06 14:13 UTC, caugner requested changes
Thank you, good catch, but let's remove the version here altogether, as https://nodejs.org/ does not directly offer to install an older version anyways.

Like this, we won't ever forget updating the version here.

2023-03-07 01:46 UTC, daiwanxing commented
> Thank you, good catch, but let's remove the version here altogether, as https://nodejs.org/ does not directly offer to install an older version anyways.
> 
> Like this, we won't ever forget updating the version here.

Thanks for your suggestion.

2023-03-09 20:10 UTC, caugner requested changes
LGTM, just some nits:
1. Markdown automatically increments enumerated lists, so we don't need to do this ourselves.
2. Make sure to run `yarn prettier-format` once.
3. Please make sure to sign your commits (see [this error message](https://github.com/mdn/yari/actions/runs/4349845067/jobs/7605696206)). Once you have setup commit signatures, you can resign your commits by running `git rebase -x "git commit --amend --gpg-sign --no-edit" main`

2023-05-18 13:20 UTC, LeoMcA approved these changes

2023-05-18 13:21 UTC, merged