fix: change image's background color to transparent
mdn/yari pull request #9250
Opened 2023-07-07 04:21 UTC by CBID2

## Summary

Fixes #9130 
### Problem

The alt text of images is not visible due to the way the background color is set
### Solution

I made set the background color to `transparent` for the dark theme. This will make the alt text appear in dark mode. 
---

2023-07-07 09:29 UTC, bsmth commented
Thanks a lot for the changes! I tried this fix out myself with an image with a wrong src:

<details>
![image](https://github.com/mdn/yari/assets/43580235/4b1d6471-812f-4abd-b651-ab8cfe4972ba)

![image](https://github.com/mdn/yari/assets/43580235/ee02c80b-578c-4562-b3af-b2944805e576)
</details>

Looks good, in my opinion. I don't know if it affects any other places where we have images (pngs?) with a transparent background. It would also be great for Yari dev to have a look, also.

2023-09-28 12:41 UTC, caugner requested changes
Thank you, `transparent` works, but we should better use the `--background-primary` CSS variable instead to keep the behavior similar, which is white with the light theme and 90% black with the dark theme.

2023-09-28 12:41 UTC, caugner commented on client/src/document/index.scss
> +    background: transparent;
Let's use `--background-primary` instead to be safe:

```suggestion
    background: var(--background-primary);
```

2023-09-28 12:55 UTC, CBID2 commented
> Thank you, `transparent` works, but we should better use the `--background-primary` CSS variable instead to keep the behavior similar, which is white with the light theme and 90% black with the dark theme.

Done @caugner! :)

2023-09-28 16:46 UTC, caugner approved these changes
Thank you! 🙌

2023-09-28 18:17 UTC, merged