fix(toolbar): make suggestion diffs theme-friendly
mdn/yari pull request #9322
Opened 2023-07-17 14:47 UTC by queengooborg

## Summary

This PR updates the backgrounds of the `<ins>` and `<del>` elements inside of the flaws panel to make them theme-friendly.  This resolves an accessibility (contrast) issue.

---

## Screenshots

### Before

![before.png](https://github.com/mdn/yari/assets/5179191/755fe9c4-a08a-4648-8717-de1778823fcb)

### After

![after.png](https://github.com/mdn/yari/assets/5179191/eb8204e2-f024-49b3-bb67-7fe84cd82c85)

2023-11-17 20:46 UTC, queengooborg commented
CC @caugner @fiji-flo -- this change is a very simple one that fixes a major accessibility issue.

2023-11-18 00:06 UTC, caugner commented
@queengooborg Can you please fill out the pull request template, including "How did you test this change?"? 🙏

2023-11-18 10:20 UTC, queengooborg commented
I updated the issue description to match the template, but I've pretty much already filled out all of the applicable fields from the template.  The "How did you test this change?" doesn't apply because it's a UI update only.  .-.

2024-03-21 15:29 UTC, caugner requested changes

2024-03-21 15:29 UTC, caugner commented on client/src/ui/base/_themes.scss
> +  --background-ins: #{color.adjust($mdn-theme-light-icon-success, $alpha: -0.5)};
We're still using `--background-critical` and `--background-success`.

2024-04-04 12:11 UTC, caugner approved these changes
We (@argl @fiji-flo @caugner) took a look and approve the changes.

2024-04-04 12:11 UTC, merged