feat(theme): sync body background-color with theme-color meta tag
mdn/yari pull request #9325
Opened 2023-07-18 08:50 UTC by zica87

## Summary
Fixes #7884.

### Problem
(copied from the issue title)
> the color of status bar remains white even if dark mode is on. Because of `<meta name="theme-color" content="#ffffff" />`

### Solution

Set "theme-color" to the background color of the page(`<body>`) on
- page load
- user changes theme

---

## Screenshots

|Before|After|
|-|-|
|![screenshot before](https://github.com/mdn/yari/assets/59327276/a37b8d53-4d23-4c10-ac01-be6dbef6a45f)|![screenshot after](https://github.com/mdn/yari/assets/59327276/0cb22b12-edae-48d2-9690-b0263a9448e4)|

---

## How did you test this change?

Tested by running `yarn dev` and
- visiting on PC
  - Tried when dark mode on/off and checked that 
    - the class of `<html>` is set correctly
    - the "theme-color" meta tag's `content` (color)
      - is correct on first visiting the site and
      - changes on changing theme
  - on Vivaldi browser 6.1.3035.111 (based on chromium)
  - win10 22H2 19045
- visiting on Android phone
  - checked the status bar turns black after changing theme to Dark
  - my phone is too old that doesn't have dark mode so I can't test the color correct or not on first visiting with dark mode turned on
  - on Samsung browser 21.0.3.6 (based on chromium)
  - Android 9

> refactor(theme): remove a redundant if block

The if block is identical to line 72-74 and do nothing else.

> feat(theme): sync theme-color meta tag with theme

code copied from https://github.com/rust-lang/mdBook/pull/547

> fix(theme): properly initialize theme

I guess the `useEffect` (line 53) is for setting theme on page load, so I think put `activeTheme` in the dependency list (line 64) is a mistake and thus removed it.

I added `?? "os-default"` to properly set "theme-color" meta tag when:
- the user uses dark mode
- and either
  - the user didn't select a theme manually (so `localStorage.getItem` returns `null`)
  - or `localStorage.getItem` throws error

Setting theme here has a downside that "theme-color" meta tag will not be set until the content has loaded.
But I think it's OK because:
- The loading is fast on real `developer.mozilla.org`. I have never seen the loading screen before testing this PR on local.
- Users can be hinted by the status bar turning black that "the page has finished loading".
- The implementation (this PR) is simpler.

2023-10-26 10:39 UTC, zica87 commented
@caugner May I get any response?

2023-10-27 18:46 UTC, caugner requested changes
LGTM, just one nit.

2023-10-27 18:46 UTC, caugner commented on client/src/utils.ts
> +      )!.content = getComputedStyle(document.body).backgroundColor;
Let's be more cautious here:

```suggestion
      const meta = document.querySelector<HTMLMetaElement>(
        'meta[name="theme-color"]'
      );
      const color = getComputedStyle(document.body).backgroundColor;
      if (meta && color) {
        meta.content = color;
      }
```

2023-10-30 20:33 UTC, caugner approved these changes
Thanks, LGTM, tested locally. 🙌

2023-10-30 20:41 UTC, merged