Pong2
mdn/yari pull request #9775
Opened 2023-10-09 08:34 UTC by fiji-flo

## Summary

Remove unused Carbon fallback and support BSA.

---

## How did you test this change?

Staging.

2023-10-09 08:35 UTC, fiji-flo commented on libs/pong/cc2ip.js
> +  return cc2ip[countryCode] ?? "10.10.10.10";
IPs and fallback was provided by BSA.

2023-10-11 15:37 UTC, LeoMcA requested changes
One thing actually seems like a bug (the `copy` -> `description` suggestion), the rest is relatively nitty - looks good!

2023-10-11 15:37 UTC, LeoMcA commented on libs/pong/pong2.js
> +    const res = await fetch(`https:${click}`, { redirect: "follow" });
I think it might be best to catch a `null` `click` value, if verification fails, so we don't attempt to fetch `https:null`

2023-10-11 15:37 UTC, LeoMcA commented on libs/pong/pong2.js
> +    await fetch(`https:${view}`, {
Same here with catching a `null` value

2023-10-12 14:36 UTC, fiji-flo reviewed
I added a version in the payload to route as the click will not have the referrer set. We'll remove this after the migration.

2023-10-13 15:18 UTC, LeoMcA approved these changes
code looks good, attempted to test on stage but I don't think these latest changes have been deployed there?

2023-10-25 08:04 UTC, merged