Chore: Fix typos
mdn/yari pull request #9858
Opened 2023-10-20 05:16 UTC by thapasusheel

## Summary

This PR fix the typos seen in various files

```pseudo
Instanciated > Instantiated
prooved > proved
wil > wil
protoype > prototype
supressed > suppressed
```

2023-10-30 12:01 UTC, caugner approved these changes
Good catch, thank you!

2023-10-30 12:12 UTC, caugner requested changes

2023-10-30 12:12 UTC, caugner commented on client/src/settings/db.ts
> +  // (just to inform Typescript. Instantiated by Dexie in stores() method)
Can you please replicate this change in `client/pwa/src/db.ts`? 🙏

2023-10-31 02:30 UTC, thapasusheel commented
@caugner  I have done as  you have asked. Can you review it?

2023-10-31 09:23 UTC, caugner approved these changes

2023-10-31 09:24 UTC, merged