fix(css): transparent images in dark mode issue
mdn/yari pull request #9863
Opened 2023-10-21 08:34 UTC by OnkarRuikar

- fixes https://github.com/mdn/content/issues/29755
- related to https://github.com/mdn/content/pull/29698

## Summary

The PR https://github.com/mdn/yari/pull/9250 caused a regression. It changed background color of all the images from `white` to `transparent`. Now all the transparent images in `mdn/content` are facing issues in dark mode: black lines, black text, and black boxes are appearing invisible.

### Problem

Set page in dark mode.

Before the regression: https://web.archive.org/web/20230601124043/https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate#the_rendering_waterfall

After the regression: https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate#the_rendering_waterfall

Before regression:
![_1](https://github.com/mdn/yari/assets/87750369/8e34bafa-c279-45aa-b6c6-33341347907d)

After regression:
![before](https://github.com/mdn/yari/assets/87750369/5e97789b-e98f-437a-a1ab-17cf7971f861)

### Solution

It is not feasible to make all the images compatible with both white and black backgrounds. Also, after the regression it is not easy to identify all the images that are affected by transparent background. We can't prevent future contributors from committing transparent illustrations.

It's better to keep the image background white. To solve original issue of alt text, set `color: black`on images.

---

## Screenshots

### Before

![before](https://github.com/mdn/yari/assets/87750369/5e97789b-e98f-437a-a1ab-17cf7971f861)

### After

![after](https://github.com/mdn/yari/assets/87750369/8e34bafa-c279-45aa-b6c6-33341347907d)

Alt text scenario
![alt text](https://github.com/mdn/yari/assets/87750369/b10dbe3e-514b-4f35-9ba6-a60f29fbddd6)

---

## How did you test this change?

In local browser after doing `yarn dev`.

2023-10-21 13:26 UTC, chrisdavidmills approved these changes
Oooo crud, yup, let's get this one merged. Thanks @OnkarRuikar!

2023-10-21 13:27 UTC, chrisdavidmills commented
> Oooo crud, yup, let's get this one merged. Thanks @OnkarRuikar!

Damn, I don't have privs to merge on this repo either. Can you handle this one @caugner, or maybe @Rumyra?

2023-10-24 09:17 UTC, caugner requested changes
LGTM, but let's add comments and change the color slightly.

2023-10-24 09:17 UTC, caugner commented on client/src/document/index.scss
> +    background: #fff;
```suggestion
    /* Required for images with black text on transparent background. */
    background: #fff;
```

2023-10-24 09:17 UTC, caugner commented on client/src/document/index.scss
> +    color: #000;
Let's use the same color as text in the light theme, and add a comment:

```suggestion
    /* Required for alt texts. */
    color: #1b1b1b;
```

2023-10-24 17:22 UTC, OnkarRuikar commented on client/src/document/index.scss
> +    background: #fff;
> 

```suggestion
    /* In dark mode, required for images with black text on transparent background. */
    background: #fff;
```

2023-10-24 18:02 UTC, caugner commented on client/src/document/index.scss
> +    background: #fff;
@OnkarRuikar I agree.

2023-10-26 17:25 UTC, caugner approved these changes
Awesome, thank you! 🎉

2023-10-26 17:29 UTC, merged